$gwx2_XC_5=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx2_XC_5 || [];
function gz$gwx2_XC_5_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx2_XC_5_1)return __WXML_GLOBAL__.ops_cached.$gwx2_XC_5_1
__WXML_GLOBAL__.ops_cached.$gwx2_XC_5_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([1,true])
Z([3,'__l'])
Z([3,'data-v-3a3f9320 vue-ref'])
Z([3,'containerRef'])
Z([[7],[3,'mx_pageScroll_top']])
Z(z[0])
Z([3,'67e32737-1'])
Z([[4],[[5],[[5],[1,'default']],[1,'bottom']]])
Z([3,'flex gap-20 gap-10 data-v-3a3f9320'])
Z([3,'bottom'])
Z(z[1])
Z([3,'__e'])
Z([3,'data-v-3a3f9320'])
Z([[4],[[5],[[4],[[5],[[5],[1,'^click']],[[4],[[5],[[4],[[5],[1,'printSelected']]]]]]]]])
Z([[6],[[7],[3,'$root']],[3,'g0']])
Z([3,'primary'])
Z([[2,'+'],[[2,'+'],[1,'67e32737-2'],[1,',']],[1,'67e32737-1']])
Z([[4],[[5],[1,'default']]])
Z([3,'打印标签'])
Z([[2,'!'],[[7],[3,'isPresale']]])
Z(z[1])
Z(z[12])
Z([3,'share'])
Z(z[0])
Z([3,'info'])
Z([[2,'+'],[[2,'+'],[1,'67e32737-3'],[1,',']],[1,'67e32737-1']])
Z(z[17])
Z([3,'转发给板车队'])
Z([3,'flex items-center gap-20 pt-20 px-24 flex-1 data-v-3a3f9320'])
Z([3,'var(--color-primary)'])
Z(z[1])
Z(z[11])
Z([[7],[3,'isAllSelected']])
Z(z[12])
Z([[4],[[5],[[4],[[5],[[5],[1,'^change']],[[4],[[5],[[4],[[5],[1,'selectAll']]]]]]]]])
Z([3,'全选'])
Z([3,'14'])
Z([3,'circle'])
Z([3,'16'])
Z([[2,'+'],[[2,'+'],[1,'67e32737-4'],[1,',']],[1,'67e32737-1']])
Z(z[1])
Z(z[11])
Z(z[12])
Z([[4],[[5],[[4],[[5],[[5],[1,'^click']],[[4],[[5],[[4],[[5],[1,'selectInverse']]]]]]]]])
Z(z[0])
Z([3,'mini'])
Z(z[15])
Z([[2,'+'],[[2,'+'],[1,'67e32737-5'],[1,',']],[1,'67e32737-1']])
Z(z[17])
Z([3,'反选'])
Z([3,'__i0__'])
Z([3,'goods'])
Z([[6],[[7],[3,'$root']],[3,'l1']])
Z([3,'supplierSkuId'])
Z([3,'mx-20 pt-20 my-20 bg-white rounded-16 data-v-3a3f9320'])
Z(z[1])
Z(z[12])
Z([[6],[[6],[[7],[3,'goods']],[3,'$orig']],[3,'gridItemList']])
Z([[6],[[7],[3,'goods']],[3,'$orig']])
Z([[2,'+'],[[2,'+'],[[2,'+'],[1,'67e32737-6-'],[[7],[3,'__i0__']]],[1,',']],[1,'67e32737-1']])
Z([[4],[[5],[[5],[[5],[1,'left']],[1,'right']],[1,'bottom']]])
Z(z[11])
Z([3,'flex items-center data-v-3a3f9320'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'selectGoods']],[[4],[[5],[1,'$0']]]],[[4],[[5],[[4],[[5],[[4],[[5],[[5],[[5],[1,'goodsList']],[1,'supplierSkuId']],[[6],[[6],[[7],[3,'goods']],[3,'$orig']],[3,'supplierSkuId']]]]]]]]]]]]]]]])
Z([3,'left'])
Z(z[29])
Z(z[1])
Z(z[11])
Z(z[11])
Z([[6],[[6],[[7],[3,'goods']],[3,'$orig']],[3,'select']])
Z(z[12])
Z([[4],[[5],[[5],[[4],[[5],[[5],[1,'^change']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'selectGoods']],[[4],[[5],[1,'$0']]]],[[4],[[5],[[4],[[5],[[4],[[5],[[5],[[5],[1,'goodsList']],[1,'supplierSkuId']],[[6],[[6],[[7],[3,'goods']],[3,'$orig']],[3,'supplierSkuId']]]]]]]]]]]]]]],[[4],[[5],[[5],[1,'^tap']],[[4],[[5],[[4],[[5],[[5],[1,'']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([3,' '])
Z(z[37])
Z([3,'20'])
Z([[2,'+'],[[2,'+'],[[2,'+'],[1,'67e32737-7-'],[[7],[3,'__i0__']]],[1,',']],[[2,'+'],[1,'67e32737-6-'],[[7],[3,'__i0__']]]])
Z([3,'flex flex-col items-center justify-center data-v-3a3f9320'])
Z([3,'right'])
Z(z[12])
Z([3,'总件数'])
Z([3,'text-error text-32 data-v-3a3f9320'])
Z([a,[[2,'+'],[[2,'+'],[1,''],[[6],[[6],[[7],[3,'goods']],[3,'$orig']],[3,'deliveryQuantity']]],[1,'件']]])
Z([3,'__i1__'])
Z([3,'customer'])
Z([[6],[[7],[3,'goods']],[3,'l0']])
Z([3,'orderItemId'])
Z(z[12])
Z(z[9])
Z([3,'flex items-center bg-gray rounded-16 m-10 px-10 data-v-3a3f9320'])
Z(z[62])
Z(z[29])
Z(z[1])
Z(z[11])
Z(z[11])
Z([[6],[[6],[[7],[3,'customer']],[3,'$orig']],[3,'select']])
Z(z[12])
Z([[4],[[5],[[5],[[4],[[5],[[5],[1,'^change']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'selectCustomer']],[[4],[[5],[[5],[1,'$0']],[1,'$1']]]],[[4],[[5],[[5],[[4],[[5],[[5],[[4],[[5],[[5],[[5],[1,'goodsList']],[1,'supplierSkuId']],[[6],[[6],[[7],[3,'goods']],[3,'$orig']],[3,'supplierSkuId']]]]],[[4],[[5],[[5],[[5],[1,'customerOrderList']],[1,'orderItemId']],[[6],[[6],[[7],[3,'customer']],[3,'$orig']],[3,'orderItemId']]]]]]],[[4],[[5],[[4],[[5],[[5],[[5],[1,'goodsList']],[1,'supplierSkuId']],[[6],[[6],[[7],[3,'goods']],[3,'$orig']],[3,'supplierSkuId']]]]]]]]]]]]]]],[[4],[[5],[[5],[1,'^tap']],[[4],[[5],[[4],[[5],[[5],[1,'']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z(z[72])
Z(z[37])
Z(z[74])
Z([[2,'+'],[[2,'+'],[[2,'+'],[[2,'+'],[[2,'+'],[1,'67e32737-8-'],[[7],[3,'__i0__']]],[1,'-']],[[7],[3,'__i1__']]],[1,',']],[[2,'+'],[1,'67e32737-6-'],[[7],[3,'__i0__']]]])
Z([3,'flex-1 data-v-3a3f9320'])
Z([3,'customer data-v-3a3f9320'])
Z([3,'customer-title data-v-3a3f9320'])
Z([3,'客户名称'])
Z([3,'customer-content data-v-3a3f9320'])
Z([a,[[2,'+'],[[2,'+'],[1,''],[[6],[[7],[3,'customer']],[3,'m0']]],[1,'']]])
Z(z[102])
Z(z[103])
Z([3,'拍子号'])
Z(z[105])
Z([a,[[2,'+'],[[2,'+'],[1,''],[[6],[[6],[[7],[3,'customer']],[3,'$orig']],[3,'deliveryNumberDesc']]],[1,'']]])
Z(z[102])
Z(z[103])
Z([3,'物流'])
Z(z[105])
Z([a,[[2,'+'],[[2,'+'],[1,''],[[6],[[6],[[7],[3,'customer']],[3,'$orig']],[3,'logisticsName']]],[1,'']]])
Z(z[102])
Z(z[103])
Z([3,'车位号'])
Z(z[105])
Z([a,[[2,'+'],[[2,'+'],[1,''],[[6],[[6],[[7],[3,'customer']],[3,'$orig']],[3,'parkingNo']]],[1,'']]])
Z(z[12])
Z(z[1])
Z(z[11])
Z(z[11])
Z(z[11])
Z(z[12])
Z([[4],[[5],[[5],[[5],[[4],[[5],[[5],[1,'^change']],[[4],[[5],[[4],[[5],[1,'handleCountChange']]]]]]]],[[4],[[5],[[5],[1,'^tap']],[[4],[[5],[[4],[[5],[[5],[1,'']],[[4],[[5],[1,'$event']]]]]]]]]],[[4],[[5],[[5],[1,'^input']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'$0']],[1,'count']],[1,'$event']],[[4],[[5]]]]]],[[4],[[5],[[4],[[5],[[5],[[4],[[5],[[5],[[5],[1,'goodsList']],[1,'supplierSkuId']],[[6],[[6],[[7],[3,'goods']],[3,'$orig']],[3,'supplierSkuId']]]]],[[4],[[5],[[5],[[5],[1,'customerOrderList']],[1,'orderItemId']],[[6],[[6],[[7],[3,'customer']],[3,'$orig']],[3,'orderItemId']]]]]]]]]]]]]]]])
Z([[6],[[6],[[7],[3,'customer']],[3,'$orig']],[3,'deliveryQuantity']])
Z([[6],[[6],[[7],[3,'customer']],[3,'$orig']],[3,'count']])
Z([[2,'+'],[[2,'+'],[[2,'+'],[[2,'+'],[[2,'+'],[1,'67e32737-9-'],[[7],[3,'__i0__']]],[1,'-']],[[7],[3,'__i1__']]],[1,',']],[[2,'+'],[1,'67e32737-6-'],[[7],[3,'__i0__']]]])
Z(z[1])
Z(z[11])
Z(z[11])
Z(z[11])
Z(z[12])
Z(z[0])
Z([[4],[[5],[[5],[[5],[[4],[[5],[[5],[1,'^confirm']],[[4],[[5],[[4],[[5],[1,'showCode']]]]]]]],[[4],[[5],[[5],[1,'^cancel']],[[4],[[5],[[4],[[5],[1,'e0']]]]]]]],[[4],[[5],[[5],[1,'^input']],[[4],[[5],[[4],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'']],[1,'showPrintModalTag']],[1,'$event']],[[4],[[5]]]]]]]]]]]]])
Z(z[0])
Z([3,'提示'])
Z([[7],[3,'showPrintModalTag']])
Z([[2,'+'],[[2,'+'],[1,'67e32737-10'],[1,',']],[1,'67e32737-1']])
Z(z[17])
Z([3,'text-main p-20 data-v-3a3f9320'])
Z(z[12])
Z([[7],[3,'printTime']])
Z(z[12])
Z([a,[[2,'+'],[[2,'+'],[1,'上次打印时间: '],[[7],[3,'printTime']]],[1,'\n']]])
Z([3,'确定要打印送货单吗？'])
})(__WXML_GLOBAL__.ops_cached.$gwx2_XC_5_1);return __WXML_GLOBAL__.ops_cached.$gwx2_XC_5_1
}
__WXML_GLOBAL__.ops_set.$gwx2_XC_5=z;
__WXML_GLOBAL__.ops_init.$gwx2_XC_5=true;
var x=['./package-supplyGoods/delivery/print.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx2_XC_5_1()
var b9P=_mz(z,'b-container',['backTop',0,'bind:__l',1,'class',1,'data-ref',2,'scrollTop',3,'useFooterSlot',4,'vueId',5,'vueSlots',6],[],e,s,gg)
var o0P=_mz(z,'view',['class',8,'slot',1],[],e,s,gg)
var oBQ=_mz(z,'b-button',['bind:__l',10,'bind:click',1,'class',2,'data-event-opts',3,'disabled',4,'type',5,'vueId',6,'vueSlots',7],[],e,s,gg)
var fCQ=_oz(z,18,e,s,gg)
_(oBQ,fCQ)
_(o0P,oBQ)
var xAQ=_v()
_(o0P,xAQ)
if(_oz(z,19,e,s,gg)){xAQ.wxVkey=1
var cDQ=_mz(z,'b-button',['bind:__l',20,'class',1,'openType',2,'plain',3,'type',4,'vueId',5,'vueSlots',6],[],e,s,gg)
var hEQ=_oz(z,27,e,s,gg)
_(cDQ,hEQ)
_(xAQ,cDQ)
}
xAQ.wxXCkey=1
xAQ.wxXCkey=3
_(b9P,o0P)
var oFQ=_n('view')
_rz(z,oFQ,'class',28,e,s,gg)
var cGQ=_mz(z,'u-checkbox',['activeColor',29,'bind:__l',1,'bind:change',2,'checked',3,'class',4,'data-event-opts',5,'label',6,'labelSize',7,'shape',8,'size',9,'vueId',10],[],e,s,gg)
_(oFQ,cGQ)
var oHQ=_mz(z,'b-button',['bind:__l',40,'bind:click',1,'class',2,'data-event-opts',3,'inlineBlock',4,'size',5,'type',6,'vueId',7,'vueSlots',8],[],e,s,gg)
var lIQ=_oz(z,49,e,s,gg)
_(oHQ,lIQ)
_(oFQ,oHQ)
_(b9P,oFQ)
var aJQ=_v()
_(b9P,aJQ)
var tKQ=function(bMQ,eLQ,oNQ,gg){
var oPQ=_n('view')
_rz(z,oPQ,'class',54,bMQ,eLQ,gg)
var fQQ=_mz(z,'bg-goods-info-card',['bind:__l',55,'class',1,'gridItemList',2,'item',3,'vueId',4,'vueSlots',5],[],bMQ,eLQ,gg)
var cRQ=_mz(z,'view',['bindtap',61,'class',1,'data-event-opts',2,'slot',3],[],bMQ,eLQ,gg)
var hSQ=_mz(z,'u-checkbox',['activeColor',65,'bind:__l',1,'bind:change',2,'catch:tap',3,'checked',4,'class',5,'data-event-opts',6,'label',7,'shape',8,'size',9,'vueId',10],[],bMQ,eLQ,gg)
_(cRQ,hSQ)
_(fQQ,cRQ)
var oTQ=_mz(z,'view',['class',76,'slot',1],[],bMQ,eLQ,gg)
var cUQ=_n('view')
_rz(z,cUQ,'class',78,bMQ,eLQ,gg)
var oVQ=_oz(z,79,bMQ,eLQ,gg)
_(cUQ,oVQ)
_(oTQ,cUQ)
var lWQ=_n('view')
_rz(z,lWQ,'class',80,bMQ,eLQ,gg)
var aXQ=_oz(z,81,bMQ,eLQ,gg)
_(lWQ,aXQ)
_(oTQ,lWQ)
_(fQQ,oTQ)
var tYQ=_v()
_(fQQ,tYQ)
var eZQ=function(o2Q,b1Q,x3Q,gg){
var f5Q=_mz(z,'view',['class',86,'slot',1],[],o2Q,b1Q,gg)
var c6Q=_n('view')
_rz(z,c6Q,'class',88,o2Q,b1Q,gg)
var h7Q=_n('view')
_rz(z,h7Q,'class',89,o2Q,b1Q,gg)
var o8Q=_mz(z,'u-checkbox',['activeColor',90,'bind:__l',1,'bind:change',2,'catch:tap',3,'checked',4,'class',5,'data-event-opts',6,'label',7,'shape',8,'size',9,'vueId',10],[],o2Q,b1Q,gg)
_(h7Q,o8Q)
_(c6Q,h7Q)
var c9Q=_n('view')
_rz(z,c9Q,'class',101,o2Q,b1Q,gg)
var o0Q=_n('view')
_rz(z,o0Q,'class',102,o2Q,b1Q,gg)
var lAR=_n('view')
_rz(z,lAR,'class',103,o2Q,b1Q,gg)
var aBR=_oz(z,104,o2Q,b1Q,gg)
_(lAR,aBR)
_(o0Q,lAR)
var tCR=_n('view')
_rz(z,tCR,'class',105,o2Q,b1Q,gg)
var eDR=_oz(z,106,o2Q,b1Q,gg)
_(tCR,eDR)
_(o0Q,tCR)
_(c9Q,o0Q)
var bER=_n('view')
_rz(z,bER,'class',107,o2Q,b1Q,gg)
var oFR=_n('view')
_rz(z,oFR,'class',108,o2Q,b1Q,gg)
var xGR=_oz(z,109,o2Q,b1Q,gg)
_(oFR,xGR)
_(bER,oFR)
var oHR=_n('view')
_rz(z,oHR,'class',110,o2Q,b1Q,gg)
var fIR=_oz(z,111,o2Q,b1Q,gg)
_(oHR,fIR)
_(bER,oHR)
_(c9Q,bER)
var cJR=_n('view')
_rz(z,cJR,'class',112,o2Q,b1Q,gg)
var hKR=_n('view')
_rz(z,hKR,'class',113,o2Q,b1Q,gg)
var oLR=_oz(z,114,o2Q,b1Q,gg)
_(hKR,oLR)
_(cJR,hKR)
var cMR=_n('view')
_rz(z,cMR,'class',115,o2Q,b1Q,gg)
var oNR=_oz(z,116,o2Q,b1Q,gg)
_(cMR,oNR)
_(cJR,cMR)
_(c9Q,cJR)
var lOR=_n('view')
_rz(z,lOR,'class',117,o2Q,b1Q,gg)
var aPR=_n('view')
_rz(z,aPR,'class',118,o2Q,b1Q,gg)
var tQR=_oz(z,119,o2Q,b1Q,gg)
_(aPR,tQR)
_(lOR,aPR)
var eRR=_n('view')
_rz(z,eRR,'class',120,o2Q,b1Q,gg)
var bSR=_oz(z,121,o2Q,b1Q,gg)
_(eRR,bSR)
_(lOR,eRR)
_(c9Q,lOR)
_(c6Q,c9Q)
var oTR=_n('view')
_rz(z,oTR,'class',122,o2Q,b1Q,gg)
var xUR=_mz(z,'b-number-box',['bind:__l',123,'bind:change',1,'bind:input',2,'catch:tap',3,'class',4,'data-event-opts',5,'max',6,'value',7,'vueId',8],[],o2Q,b1Q,gg)
_(oTR,xUR)
_(c6Q,oTR)
_(f5Q,c6Q)
_(x3Q,f5Q)
return x3Q
}
tYQ.wxXCkey=4
_2z(z,84,eZQ,bMQ,eLQ,gg,tYQ,'customer','__i1__','orderItemId')
_(oPQ,fQQ)
_(oNQ,oPQ)
return oNQ
}
aJQ.wxXCkey=4
_2z(z,52,tKQ,e,s,gg,aJQ,'goods','__i0__','supplierSkuId')
var oVR=_mz(z,'b-modal',['bind:__l',132,'bind:cancel',1,'bind:confirm',2,'bind:input',3,'class',4,'closeOnClickOverlay',5,'data-event-opts',6,'showCancelButton',7,'title',8,'value',9,'vueId',10,'vueSlots',11],[],e,s,gg)
var fWR=_n('view')
_rz(z,fWR,'class',144,e,s,gg)
var cXR=_n('view')
_rz(z,cXR,'class',145,e,s,gg)
var hYR=_v()
_(cXR,hYR)
if(_oz(z,146,e,s,gg)){hYR.wxVkey=1
var oZR=_n('text')
_rz(z,oZR,'class',147,e,s,gg)
var c1R=_oz(z,148,e,s,gg)
_(oZR,c1R)
_(hYR,oZR)
}
var o2R=_oz(z,149,e,s,gg)
_(cXR,o2R)
hYR.wxXCkey=1
_(fWR,cXR)
_(oVR,fWR)
_(b9P,oVR)
_(r,b9P)
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx2_XC_5";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx2_XC_5();	if (__vd_version_info__.delayedGwx) __wxAppCode__['package-supplyGoods/delivery/print.wxml'] = [$gwx2_XC_5, './package-supplyGoods/delivery/print.wxml'];else __wxAppCode__['package-supplyGoods/delivery/print.wxml'] = $gwx2_XC_5( './package-supplyGoods/delivery/print.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['package-supplyGoods/delivery/print.wxss']=setCssToHead([".",[1],"customer.",[1],"data-v-3a3f9320{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex:1;flex:1;padding:",[0,10],"}\n.",[1],"customer-title.",[1],"data-v-3a3f9320{color:var(--color-content);font:",[0,26],"}\n.",[1],"customer-content.",[1],"data-v-3a3f9320{-webkit-align-items:center;align-items:center;color:var(--color-main);display:-webkit-flex;display:flex;-webkit-flex:1;flex:1;font-size:",[0,28],";-webkit-justify-content:flex-end;justify-content:flex-end}\n",],undefined,{path:"./package-supplyGoods/delivery/print.wxss"});
}