$gwx0_XC_3=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx0_XC_3 || [];
function gz$gwx0_XC_3_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx0_XC_3_1)return __WXML_GLOBAL__.ops_cached.$gwx0_XC_3_1
__WXML_GLOBAL__.ops_cached.$gwx0_XC_3_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'page data-v-75ceecf4'])
Z([3,'__e'])
Z(z[1])
Z([3,'scroll data-v-75ceecf4'])
Z([[4],[[5],[[5],[[4],[[5],[[5],[1,'dragstart']],[[4],[[5],[[4],[[5],[[5],[1,'hideKeyboardOnScroll']],[[4],[[5],[1,'$event']]]]]]]]]],[[4],[[5],[[5],[1,'scroll']],[[4],[[5],[[4],[[5],[[5],[1,'hideKeyboardOnScroll']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([1,true])
Z(z[5])
Z(z[5])
Z([3,'section data-v-75ceecf4'])
Z([3,'label required data-v-75ceecf4'])
Z([3,'所属总仓'])
Z(z[1])
Z([3,'picker-val data-v-75ceecf4'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'openWarehousePicker']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([[4],[[5],[[5],[1,'data-v-75ceecf4']],[[2,'?:'],[[6],[[7],[3,'form']],[3,'mainWarehouseId']],[1,''],[1,'placeholder']]]])
Z([a,[[7],[3,'warehouseText']]])
Z(z[8])
Z(z[9])
Z([3,'供应商编号'])
Z([1,false])
Z(z[1])
Z([3,'input data-v-75ceecf4'])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'$0']],[1,'supplierCode']],[1,'$event']],[[4],[[5]]]]]],[[4],[[5],[1,'form']]]]]]]]]]])
Z(z[5])
Z([3,'请输入供应商编号'])
Z([[6],[[7],[3,'form']],[3,'supplierCode']])
Z(z[8])
Z(z[9])
Z([3,'供应商名称'])
Z(z[19])
Z(z[1])
Z(z[21])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'$0']],[1,'supplierName']],[1,'$event']],[[4],[[5]]]]]],[[4],[[5],[1,'form']]]]]]]]]]])
Z(z[5])
Z([3,'请输入供应商全称'])
Z([[6],[[7],[3,'form']],[3,'supplierName']])
Z(z[8])
Z(z[9])
Z([3,'真实姓名'])
Z(z[19])
Z(z[1])
Z(z[21])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'$0']],[1,'realName']],[1,'$event']],[[4],[[5]]]]]],[[4],[[5],[1,'form']]]]]]]]]]])
Z(z[5])
Z([3,'请输入真实姓名'])
Z([[6],[[7],[3,'form']],[3,'realName']])
Z(z[8])
Z(z[9])
Z([3,'结算主体'])
Z(z[1])
Z(z[12])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'openSettlementPicker']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([[4],[[5],[[5],[1,'data-v-75ceecf4']],[[2,'?:'],[[6],[[7],[3,'form']],[3,'settlementType']],[1,''],[1,'placeholder']]]])
Z([a,[[7],[3,'settlementTypeText']]])
Z(z[8])
Z(z[9])
Z([3,'手机'])
Z(z[19])
Z(z[1])
Z(z[21])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'$0']],[1,'phone']],[1,'$event']],[[4],[[5]]]]]],[[4],[[5],[1,'form']]]]]]]]]]])
Z(z[5])
Z([3,'11'])
Z([3,'请输入手机号'])
Z([3,'digit'])
Z([[6],[[7],[3,'form']],[3,'phone']])
Z(z[8])
Z(z[9])
Z([3,'登录账号'])
Z(z[19])
Z(z[1])
Z(z[21])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'$0']],[1,'account']],[1,'$event']],[[4],[[5]]]]]],[[4],[[5],[1,'form']]]]]]]]]]])
Z(z[5])
Z([3,'请输入供应商系统登录账号'])
Z([[6],[[7],[3,'form']],[3,'account']])
Z(z[8])
Z(z[9])
Z([3,'登录密码'])
Z(z[19])
Z(z[1])
Z(z[21])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'$0']],[1,'password']],[1,'$event']],[[4],[[5]]]]]],[[4],[[5],[1,'form']]]]]]]]]]])
Z(z[5])
Z([3,'请输入登录密码'])
Z([[6],[[7],[3,'form']],[3,'password']])
Z(z[8])
Z([3,'label data-v-75ceecf4'])
Z([3,'档口号'])
Z(z[19])
Z(z[1])
Z(z[21])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'$0']],[1,'stallCode']],[1,'$event']],[[4],[[5]]]]]],[[4],[[5],[1,'form']]]]]]]]]]])
Z(z[5])
Z([3,'请输入仓库档口号'])
Z([[6],[[7],[3,'form']],[3,'stallCode']])
Z(z[8])
Z(z[9])
Z([3,'开票类型'])
Z(z[1])
Z(z[12])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'openInvoicePicker']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([[4],[[5],[[5],[1,'data-v-75ceecf4']],[[2,'?:'],[[6],[[7],[3,'form']],[3,'invoiceType']],[1,''],[1,'placeholder']]]])
Z([a,[[7],[3,'invoiceTypeText']]])
Z(z[8])
Z(z[87])
Z([3,'营业执照'])
Z([3,'upload-row data-v-75ceecf4'])
Z([[6],[[7],[3,'form']],[3,'businessLicense']])
Z([3,'thumb-wrap data-v-75ceecf4'])
Z([3,'thumb data-v-75ceecf4'])
Z([3,'aspectFill'])
Z(z[108])
Z(z[1])
Z([3,'thumb-del data-v-75ceecf4'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'clearUpload']],[[4],[[5],[1,'businessLicense']]]]]]]]]]])
Z([3,'删除'])
Z(z[1])
Z([3,'upload-btn data-v-75ceecf4'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'pickImage']],[[4],[[5],[1,'businessLicense']]]]]]]]]]])
Z([3,'upload-plus data-v-75ceecf4'])
Z([3,'+'])
Z([3,'upload-hint data-v-75ceecf4'])
Z([3,'请上传 大小不超过 5MB 格式为 png/jpg/jpeg/ico 的文件'])
Z([[2,'==='],[[6],[[7],[3,'form']],[3,'settlementType']],[1,'PUBLIC']])
Z(z[8])
Z(z[9])
Z([3,'公司名称'])
Z(z[19])
Z(z[1])
Z(z[21])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'$0']],[1,'companyName']],[1,'$event']],[[4],[[5]]]]]],[[4],[[5],[1,'form']]]]]]]]]]])
Z(z[5])
Z([3,'请输入公司名称(营业执照名称)'])
Z([[6],[[7],[3,'form']],[3,'companyName']])
Z(z[124])
Z(z[8])
Z(z[9])
Z([3,'营业执照编号'])
Z(z[19])
Z(z[1])
Z(z[21])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'$0']],[1,'licenceNo']],[1,'$event']],[[4],[[5]]]]]],[[4],[[5],[1,'form']]]]]]]]]]])
Z(z[5])
Z([3,'请输入营业执照编号'])
Z([[6],[[7],[3,'form']],[3,'licenceNo']])
Z(z[124])
Z(z[8])
Z(z[9])
Z([3,'执照类型'])
Z(z[1])
Z(z[12])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'openMerchantTypePicker']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([[4],[[5],[[5],[1,'data-v-75ceecf4']],[[2,'?:'],[[6],[[7],[3,'form']],[3,'merchantType']],[1,''],[1,'placeholder']]]])
Z([a,[[7],[3,'merchantTypeText']]])
Z(z[124])
Z(z[8])
Z(z[9])
Z([3,'法人姓名'])
Z(z[19])
Z(z[1])
Z(z[21])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'$0']],[1,'legalName']],[1,'$event']],[[4],[[5]]]]]],[[4],[[5],[1,'form']]]]]]]]]]])
Z(z[5])
Z([3,'请输入法人姓名'])
Z([[6],[[7],[3,'form']],[3,'legalName']])
Z(z[124])
Z(z[8])
Z(z[9])
Z([3,'法人身份证号'])
Z(z[19])
Z(z[1])
Z(z[21])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'$0']],[1,'legalLicenceNo']],[1,'$event']],[[4],[[5]]]]]],[[4],[[5],[1,'form']]]]]]]]]]])
Z(z[5])
Z([3,'请输入法人身份证号'])
Z([[6],[[7],[3,'form']],[3,'legalLicenceNo']])
Z(z[124])
Z(z[8])
Z(z[9])
Z([3,'开户许可证'])
Z(z[107])
Z([[6],[[7],[3,'form']],[3,'bankImg']])
Z(z[109])
Z(z[110])
Z(z[111])
Z(z[182])
Z(z[1])
Z(z[114])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'clearUpload']],[[4],[[5],[1,'bankImg']]]]]]]]]]])
Z(z[116])
Z(z[1])
Z(z[118])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'pickImage']],[[4],[[5],[1,'bankImg']]]]]]]]]]])
Z(z[120])
Z(z[121])
Z(z[122])
Z(z[123])
Z(z[8])
Z(z[87])
Z([3,'身份证(头像)'])
Z(z[107])
Z([[6],[[7],[3,'form']],[3,'idCardAvatar']])
Z(z[109])
Z(z[110])
Z(z[111])
Z(z[202])
Z(z[1])
Z(z[114])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'clearUpload']],[[4],[[5],[1,'idCardAvatar']]]]]]]]]]])
Z(z[116])
Z(z[1])
Z(z[118])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'pickImage']],[[4],[[5],[1,'idCardAvatar']]]]]]]]]]])
Z(z[120])
Z(z[121])
Z(z[122])
Z(z[123])
Z(z[8])
Z(z[87])
Z([3,'身份证(国徽)'])
Z(z[107])
Z([[6],[[7],[3,'form']],[3,'idCardNational']])
Z(z[109])
Z(z[110])
Z(z[111])
Z(z[222])
Z(z[1])
Z(z[114])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'clearUpload']],[[4],[[5],[1,'idCardNational']]]]]]]]]]])
Z(z[116])
Z(z[1])
Z(z[118])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'pickImage']],[[4],[[5],[1,'idCardNational']]]]]]]]]]])
Z(z[120])
Z(z[121])
Z(z[122])
Z(z[123])
Z([[2,'!=='],[[6],[[7],[3,'form']],[3,'settlementType']],[1,'PUBLIC']])
Z(z[8])
Z(z[9])
Z([3,'身份证号'])
Z(z[19])
Z(z[1])
Z(z[21])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'$0']],[1,'idCardNo']],[1,'$event']],[[4],[[5]]]]]],[[4],[[5],[1,'form']]]]]]]]]]])
Z(z[5])
Z([3,'请输入身份证号'])
Z([3,'idcard'])
Z([[6],[[7],[3,'form']],[3,'idCardNo']])
Z(z[8])
Z(z[9])
Z([3,'开户行'])
Z(z[1])
Z(z[12])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'openBankPanel']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([[4],[[5],[[5],[1,'data-v-75ceecf4']],[[2,'?:'],[[6],[[7],[3,'form']],[3,'bankName']],[1,''],[1,'placeholder']]]])
Z([a,[[7],[3,'bankText']]])
Z(z[8])
Z(z[87])
Z([3,'银行编码'])
Z(z[1])
Z(z[21])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'$0']],[1,'bankCode']],[1,'$event']],[[4],[[5]]]]]],[[4],[[5],[1,'form']]]]]]]]]]])
Z(z[5])
Z([3,'固定编码'])
Z([[6],[[7],[3,'form']],[3,'bankCode']])
Z(z[8])
Z(z[87])
Z([3,'银行卡号'])
Z(z[19])
Z(z[1])
Z(z[21])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'$0']],[1,'bankCardNo']],[1,'$event']],[[4],[[5]]]]]],[[4],[[5],[1,'form']]]]]]]]]]])
Z(z[5])
Z([3,'请输入银行卡号'])
Z(z[64])
Z([[6],[[7],[3,'form']],[3,'bankCardNo']])
Z([3,'foot-space data-v-75ceecf4'])
Z([3,'bottom-bar data-v-75ceecf4'])
Z([3,'privacy-wrap data-v-75ceecf4'])
Z(z[1])
Z([3,'data-v-75ceecf4'])
Z([[4],[[5],[[4],[[5],[[5],[1,'change']],[[4],[[5],[[4],[[5],[[5],[1,'onPrivacyCheckboxChange']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([3,'privacy-label data-v-75ceecf4'])
Z([[7],[3,'agreePrivacy']])
Z(z[282])
Z([3,'#4ab83a'])
Z([3,'1'])
Z([3,'privacy-text data-v-75ceecf4'])
Z([3,'我已阅读并同意'])
Z(z[1])
Z([3,'privacy-link data-v-75ceecf4'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'openPrivacyPolicy']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([3,'《隐私政策》'])
Z(z[1])
Z([3,'btn-submit data-v-75ceecf4'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'onSubmit']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([[7],[3,'submitLoading']])
Z([3,'注册'])
Z(z[1])
Z([3,'btn-back data-v-75ceecf4'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'goLogin']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([3,'返回登录'])
Z([[7],[3,'warehousePanelVisible']])
Z(z[1])
Z([3,'bank-mask data-v-75ceecf4'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'closeWarehousePanel']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z(z[1])
Z([3,'bank-panel data-v-75ceecf4'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([3,'bank-head data-v-75ceecf4'])
Z([3,'bank-title data-v-75ceecf4'])
Z([3,'选择所属总仓'])
Z(z[1])
Z([3,'bank-close data-v-75ceecf4'])
Z(z[307])
Z([3,'关闭'])
Z([3,'bank-list data-v-75ceecf4'])
Z(z[5])
Z(z[19])
Z([[2,'==='],[[6],[[7],[3,'$root']],[3,'g0']],[1,0]])
Z([3,'bank-empty data-v-75ceecf4'])
Z([3,'暂无总仓数据'])
Z([3,'idx'])
Z([3,'item'])
Z([[6],[[7],[3,'$root']],[3,'l0']])
Z(z[1])
Z([3,'bank-item data-v-75ceecf4'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'onWarehouseItemTap']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([[7],[3,'idx']])
Z([a,[[2,'+'],[[2,'+'],[1,''],[[6],[[7],[3,'item']],[3,'m0']]],[1,'']]])
Z([[7],[3,'bankPanelVisible']])
Z(z[1])
Z(z[306])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'closeBankPanel']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z(z[1])
Z(z[309])
Z(z[310])
Z([[2,'+'],[[2,'+'],[1,'transform:'],[[2,'?:'],[[7],[3,'bankKeyboardHeight']],[[2,'+'],[[2,'+'],[1,'translateY(-'],[[7],[3,'bankKeyboardHeight']]],[1,'px)']],[1,'none']]],[1,';']])
Z(z[311])
Z(z[312])
Z([3,'选择开户行'])
Z(z[1])
Z(z[315])
Z(z[335])
Z(z[317])
Z(z[19])
Z(z[1])
Z(z[1])
Z(z[1])
Z([3,'bank-search data-v-75ceecf4'])
Z([[4],[[5],[[5],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[5],[[4],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'']],[1,'bankKeyword']],[1,'$event']],[[4],[[5]]]]]]]],[[4],[[5],[[5],[1,'onBankKeywordInput']],[[4],[[5],[1,'$event']]]]]]]]]],[[4],[[5],[[5],[1,'focus']],[[4],[[5],[[4],[[5],[[5],[1,'onBankSearchFocus']],[[4],[[5],[1,'$event']]]]]]]]]],[[4],[[5],[[5],[1,'blur']],[[4],[[5],[[4],[[5],[[5],[1,'onBankSearchBlur']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z(z[5])
Z([3,'请输入银行名称搜索，如：中国银行'])
Z([[7],[3,'bankKeyword']])
Z(z[318])
Z(z[5])
Z(z[19])
Z([[2,'+'],[[2,'+'],[1,'max-height:'],[[2,'?:'],[[7],[3,'bankKeyboardHeight']],[[2,'+'],[[2,'+'],[1,'calc(50vh - '],[[7],[3,'bankKeyboardHeight']]],[1,'px)']],[1,'50vh']]],[1,';']])
Z([[7],[3,'bankSearching']])
Z(z[322])
Z([3,'搜索中...'])
Z([[2,'!'],[[6],[[7],[3,'$root']],[3,'g1']]])
Z(z[322])
Z([3,'请输入银行名称搜索'])
Z([[2,'==='],[[6],[[7],[3,'$root']],[3,'g2']],[1,0]])
Z(z[322])
Z([3,'无匹配开户行'])
Z(z[324])
Z(z[325])
Z([[7],[3,'bankList']])
Z(z[1])
Z(z[328])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'onBankItemTap']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z(z[330])
Z([a,[[2,'+'],[[2,'+'],[1,''],[[2,'||'],[[6],[[7],[3,'item']],[3,'bankName']],[1,'-']]],[1,'']]])
Z([3,'__l'])
Z(z[282])
Z([3,'440f3292-1'])
})(__WXML_GLOBAL__.ops_cached.$gwx0_XC_3_1);return __WXML_GLOBAL__.ops_cached.$gwx0_XC_3_1
}
__WXML_GLOBAL__.ops_set.$gwx0_XC_3=z;
__WXML_GLOBAL__.ops_init.$gwx0_XC_3=true;
var x=['./sub-pages/auth/register.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx0_XC_3_1()
var t5D=_n('view')
_rz(z,t5D,'class',0,e,s,gg)
var o8D=_mz(z,'scroll-view',['binddragstart',1,'bindscroll',1,'class',2,'data-event-opts',3,'enhanced',4,'scrollY',5,'showScrollbar',6],[],e,s,gg)
var oFE=_n('view')
_rz(z,oFE,'class',8,e,s,gg)
var lGE=_n('view')
_rz(z,lGE,'class',9,e,s,gg)
var aHE=_oz(z,10,e,s,gg)
_(lGE,aHE)
_(oFE,lGE)
var tIE=_mz(z,'view',['bindtap',11,'class',1,'data-event-opts',2],[],e,s,gg)
var eJE=_n('text')
_rz(z,eJE,'class',14,e,s,gg)
var bKE=_oz(z,15,e,s,gg)
_(eJE,bKE)
_(tIE,eJE)
_(oFE,tIE)
_(o8D,oFE)
var oLE=_n('view')
_rz(z,oLE,'class',16,e,s,gg)
var xME=_n('view')
_rz(z,xME,'class',17,e,s,gg)
var oNE=_oz(z,18,e,s,gg)
_(xME,oNE)
_(oLE,xME)
var fOE=_mz(z,'input',['adjustPosition',19,'bindinput',1,'class',2,'data-event-opts',3,'holdKeyboard',4,'placeholder',5,'value',6],[],e,s,gg)
_(oLE,fOE)
_(o8D,oLE)
var cPE=_n('view')
_rz(z,cPE,'class',26,e,s,gg)
var hQE=_n('view')
_rz(z,hQE,'class',27,e,s,gg)
var oRE=_oz(z,28,e,s,gg)
_(hQE,oRE)
_(cPE,hQE)
var cSE=_mz(z,'input',['adjustPosition',29,'bindinput',1,'class',2,'data-event-opts',3,'holdKeyboard',4,'placeholder',5,'value',6],[],e,s,gg)
_(cPE,cSE)
_(o8D,cPE)
var oTE=_n('view')
_rz(z,oTE,'class',36,e,s,gg)
var lUE=_n('view')
_rz(z,lUE,'class',37,e,s,gg)
var aVE=_oz(z,38,e,s,gg)
_(lUE,aVE)
_(oTE,lUE)
var tWE=_mz(z,'input',['adjustPosition',39,'bindinput',1,'class',2,'data-event-opts',3,'holdKeyboard',4,'placeholder',5,'value',6],[],e,s,gg)
_(oTE,tWE)
_(o8D,oTE)
var eXE=_n('view')
_rz(z,eXE,'class',46,e,s,gg)
var bYE=_n('view')
_rz(z,bYE,'class',47,e,s,gg)
var oZE=_oz(z,48,e,s,gg)
_(bYE,oZE)
_(eXE,bYE)
var x1E=_mz(z,'view',['bindtap',49,'class',1,'data-event-opts',2],[],e,s,gg)
var o2E=_n('text')
_rz(z,o2E,'class',52,e,s,gg)
var f3E=_oz(z,53,e,s,gg)
_(o2E,f3E)
_(x1E,o2E)
_(eXE,x1E)
_(o8D,eXE)
var c4E=_n('view')
_rz(z,c4E,'class',54,e,s,gg)
var h5E=_n('view')
_rz(z,h5E,'class',55,e,s,gg)
var o6E=_oz(z,56,e,s,gg)
_(h5E,o6E)
_(c4E,h5E)
var c7E=_mz(z,'input',['adjustPosition',57,'bindinput',1,'class',2,'data-event-opts',3,'holdKeyboard',4,'maxlength',5,'placeholder',6,'type',7,'value',8],[],e,s,gg)
_(c4E,c7E)
_(o8D,c4E)
var o8E=_n('view')
_rz(z,o8E,'class',66,e,s,gg)
var l9E=_n('view')
_rz(z,l9E,'class',67,e,s,gg)
var a0E=_oz(z,68,e,s,gg)
_(l9E,a0E)
_(o8E,l9E)
var tAF=_mz(z,'input',['adjustPosition',69,'bindinput',1,'class',2,'data-event-opts',3,'holdKeyboard',4,'placeholder',5,'value',6],[],e,s,gg)
_(o8E,tAF)
_(o8D,o8E)
var eBF=_n('view')
_rz(z,eBF,'class',76,e,s,gg)
var bCF=_n('view')
_rz(z,bCF,'class',77,e,s,gg)
var oDF=_oz(z,78,e,s,gg)
_(bCF,oDF)
_(eBF,bCF)
var xEF=_mz(z,'input',['adjustPosition',79,'bindinput',1,'class',2,'data-event-opts',3,'holdKeyboard',4,'placeholder',5,'value',6],[],e,s,gg)
_(eBF,xEF)
_(o8D,eBF)
var oFF=_n('view')
_rz(z,oFF,'class',86,e,s,gg)
var fGF=_n('view')
_rz(z,fGF,'class',87,e,s,gg)
var cHF=_oz(z,88,e,s,gg)
_(fGF,cHF)
_(oFF,fGF)
var hIF=_mz(z,'input',['adjustPosition',89,'bindinput',1,'class',2,'data-event-opts',3,'holdKeyboard',4,'placeholder',5,'value',6],[],e,s,gg)
_(oFF,hIF)
_(o8D,oFF)
var oJF=_n('view')
_rz(z,oJF,'class',96,e,s,gg)
var cKF=_n('view')
_rz(z,cKF,'class',97,e,s,gg)
var oLF=_oz(z,98,e,s,gg)
_(cKF,oLF)
_(oJF,cKF)
var lMF=_mz(z,'view',['bindtap',99,'class',1,'data-event-opts',2],[],e,s,gg)
var aNF=_n('text')
_rz(z,aNF,'class',102,e,s,gg)
var tOF=_oz(z,103,e,s,gg)
_(aNF,tOF)
_(lMF,aNF)
_(oJF,lMF)
_(o8D,oJF)
var ePF=_n('view')
_rz(z,ePF,'class',104,e,s,gg)
var bQF=_n('view')
_rz(z,bQF,'class',105,e,s,gg)
var oRF=_oz(z,106,e,s,gg)
_(bQF,oRF)
_(ePF,bQF)
var xSF=_n('view')
_rz(z,xSF,'class',107,e,s,gg)
var oTF=_v()
_(xSF,oTF)
if(_oz(z,108,e,s,gg)){oTF.wxVkey=1
var fUF=_n('view')
_rz(z,fUF,'class',109,e,s,gg)
var cVF=_mz(z,'image',['class',110,'mode',1,'src',2],[],e,s,gg)
_(fUF,cVF)
var hWF=_mz(z,'text',['bindtap',113,'class',1,'data-event-opts',2],[],e,s,gg)
var oXF=_oz(z,116,e,s,gg)
_(hWF,oXF)
_(fUF,hWF)
_(oTF,fUF)
}
else{oTF.wxVkey=2
var cYF=_mz(z,'view',['bindtap',117,'class',1,'data-event-opts',2],[],e,s,gg)
var oZF=_n('text')
_rz(z,oZF,'class',120,e,s,gg)
var l1F=_oz(z,121,e,s,gg)
_(oZF,l1F)
_(cYF,oZF)
_(oTF,cYF)
}
oTF.wxXCkey=1
_(ePF,xSF)
var a2F=_n('text')
_rz(z,a2F,'class',122,e,s,gg)
var t3F=_oz(z,123,e,s,gg)
_(a2F,t3F)
_(ePF,a2F)
_(o8D,ePF)
var x9D=_v()
_(o8D,x9D)
if(_oz(z,124,e,s,gg)){x9D.wxVkey=1
var e4F=_n('view')
_rz(z,e4F,'class',125,e,s,gg)
var b5F=_n('view')
_rz(z,b5F,'class',126,e,s,gg)
var o6F=_oz(z,127,e,s,gg)
_(b5F,o6F)
_(e4F,b5F)
var x7F=_mz(z,'input',['adjustPosition',128,'bindinput',1,'class',2,'data-event-opts',3,'holdKeyboard',4,'placeholder',5,'value',6],[],e,s,gg)
_(e4F,x7F)
_(x9D,e4F)
}
var o0D=_v()
_(o8D,o0D)
if(_oz(z,135,e,s,gg)){o0D.wxVkey=1
var o8F=_n('view')
_rz(z,o8F,'class',136,e,s,gg)
var f9F=_n('view')
_rz(z,f9F,'class',137,e,s,gg)
var c0F=_oz(z,138,e,s,gg)
_(f9F,c0F)
_(o8F,f9F)
var hAG=_mz(z,'input',['adjustPosition',139,'bindinput',1,'class',2,'data-event-opts',3,'holdKeyboard',4,'placeholder',5,'value',6],[],e,s,gg)
_(o8F,hAG)
_(o0D,o8F)
}
var fAE=_v()
_(o8D,fAE)
if(_oz(z,146,e,s,gg)){fAE.wxVkey=1
var oBG=_n('view')
_rz(z,oBG,'class',147,e,s,gg)
var cCG=_n('view')
_rz(z,cCG,'class',148,e,s,gg)
var oDG=_oz(z,149,e,s,gg)
_(cCG,oDG)
_(oBG,cCG)
var lEG=_mz(z,'view',['bindtap',150,'class',1,'data-event-opts',2],[],e,s,gg)
var aFG=_n('text')
_rz(z,aFG,'class',153,e,s,gg)
var tGG=_oz(z,154,e,s,gg)
_(aFG,tGG)
_(lEG,aFG)
_(oBG,lEG)
_(fAE,oBG)
}
var cBE=_v()
_(o8D,cBE)
if(_oz(z,155,e,s,gg)){cBE.wxVkey=1
var eHG=_n('view')
_rz(z,eHG,'class',156,e,s,gg)
var bIG=_n('view')
_rz(z,bIG,'class',157,e,s,gg)
var oJG=_oz(z,158,e,s,gg)
_(bIG,oJG)
_(eHG,bIG)
var xKG=_mz(z,'input',['adjustPosition',159,'bindinput',1,'class',2,'data-event-opts',3,'holdKeyboard',4,'placeholder',5,'value',6],[],e,s,gg)
_(eHG,xKG)
_(cBE,eHG)
}
var hCE=_v()
_(o8D,hCE)
if(_oz(z,166,e,s,gg)){hCE.wxVkey=1
var oLG=_n('view')
_rz(z,oLG,'class',167,e,s,gg)
var fMG=_n('view')
_rz(z,fMG,'class',168,e,s,gg)
var cNG=_oz(z,169,e,s,gg)
_(fMG,cNG)
_(oLG,fMG)
var hOG=_mz(z,'input',['adjustPosition',170,'bindinput',1,'class',2,'data-event-opts',3,'holdKeyboard',4,'placeholder',5,'value',6],[],e,s,gg)
_(oLG,hOG)
_(hCE,oLG)
}
var oDE=_v()
_(o8D,oDE)
if(_oz(z,177,e,s,gg)){oDE.wxVkey=1
var oPG=_n('view')
_rz(z,oPG,'class',178,e,s,gg)
var cQG=_n('view')
_rz(z,cQG,'class',179,e,s,gg)
var oRG=_oz(z,180,e,s,gg)
_(cQG,oRG)
_(oPG,cQG)
var lSG=_n('view')
_rz(z,lSG,'class',181,e,s,gg)
var aTG=_v()
_(lSG,aTG)
if(_oz(z,182,e,s,gg)){aTG.wxVkey=1
var tUG=_n('view')
_rz(z,tUG,'class',183,e,s,gg)
var eVG=_mz(z,'image',['class',184,'mode',1,'src',2],[],e,s,gg)
_(tUG,eVG)
var bWG=_mz(z,'text',['bindtap',187,'class',1,'data-event-opts',2],[],e,s,gg)
var oXG=_oz(z,190,e,s,gg)
_(bWG,oXG)
_(tUG,bWG)
_(aTG,tUG)
}
else{aTG.wxVkey=2
var xYG=_mz(z,'view',['bindtap',191,'class',1,'data-event-opts',2],[],e,s,gg)
var oZG=_n('text')
_rz(z,oZG,'class',194,e,s,gg)
var f1G=_oz(z,195,e,s,gg)
_(oZG,f1G)
_(xYG,oZG)
_(aTG,xYG)
}
aTG.wxXCkey=1
_(oPG,lSG)
var c2G=_n('text')
_rz(z,c2G,'class',196,e,s,gg)
var h3G=_oz(z,197,e,s,gg)
_(c2G,h3G)
_(oPG,c2G)
_(oDE,oPG)
}
var o4G=_n('view')
_rz(z,o4G,'class',198,e,s,gg)
var c5G=_n('view')
_rz(z,c5G,'class',199,e,s,gg)
var o6G=_oz(z,200,e,s,gg)
_(c5G,o6G)
_(o4G,c5G)
var l7G=_n('view')
_rz(z,l7G,'class',201,e,s,gg)
var a8G=_v()
_(l7G,a8G)
if(_oz(z,202,e,s,gg)){a8G.wxVkey=1
var t9G=_n('view')
_rz(z,t9G,'class',203,e,s,gg)
var e0G=_mz(z,'image',['class',204,'mode',1,'src',2],[],e,s,gg)
_(t9G,e0G)
var bAH=_mz(z,'text',['bindtap',207,'class',1,'data-event-opts',2],[],e,s,gg)
var oBH=_oz(z,210,e,s,gg)
_(bAH,oBH)
_(t9G,bAH)
_(a8G,t9G)
}
else{a8G.wxVkey=2
var xCH=_mz(z,'view',['bindtap',211,'class',1,'data-event-opts',2],[],e,s,gg)
var oDH=_n('text')
_rz(z,oDH,'class',214,e,s,gg)
var fEH=_oz(z,215,e,s,gg)
_(oDH,fEH)
_(xCH,oDH)
_(a8G,xCH)
}
a8G.wxXCkey=1
_(o4G,l7G)
var cFH=_n('text')
_rz(z,cFH,'class',216,e,s,gg)
var hGH=_oz(z,217,e,s,gg)
_(cFH,hGH)
_(o4G,cFH)
_(o8D,o4G)
var oHH=_n('view')
_rz(z,oHH,'class',218,e,s,gg)
var cIH=_n('view')
_rz(z,cIH,'class',219,e,s,gg)
var oJH=_oz(z,220,e,s,gg)
_(cIH,oJH)
_(oHH,cIH)
var lKH=_n('view')
_rz(z,lKH,'class',221,e,s,gg)
var aLH=_v()
_(lKH,aLH)
if(_oz(z,222,e,s,gg)){aLH.wxVkey=1
var tMH=_n('view')
_rz(z,tMH,'class',223,e,s,gg)
var eNH=_mz(z,'image',['class',224,'mode',1,'src',2],[],e,s,gg)
_(tMH,eNH)
var bOH=_mz(z,'text',['bindtap',227,'class',1,'data-event-opts',2],[],e,s,gg)
var oPH=_oz(z,230,e,s,gg)
_(bOH,oPH)
_(tMH,bOH)
_(aLH,tMH)
}
else{aLH.wxVkey=2
var xQH=_mz(z,'view',['bindtap',231,'class',1,'data-event-opts',2],[],e,s,gg)
var oRH=_n('text')
_rz(z,oRH,'class',234,e,s,gg)
var fSH=_oz(z,235,e,s,gg)
_(oRH,fSH)
_(xQH,oRH)
_(aLH,xQH)
}
aLH.wxXCkey=1
_(oHH,lKH)
var cTH=_n('text')
_rz(z,cTH,'class',236,e,s,gg)
var hUH=_oz(z,237,e,s,gg)
_(cTH,hUH)
_(oHH,cTH)
_(o8D,oHH)
var cEE=_v()
_(o8D,cEE)
if(_oz(z,238,e,s,gg)){cEE.wxVkey=1
var oVH=_n('view')
_rz(z,oVH,'class',239,e,s,gg)
var cWH=_n('view')
_rz(z,cWH,'class',240,e,s,gg)
var oXH=_oz(z,241,e,s,gg)
_(cWH,oXH)
_(oVH,cWH)
var lYH=_mz(z,'input',['adjustPosition',242,'bindinput',1,'class',2,'data-event-opts',3,'holdKeyboard',4,'placeholder',5,'type',6,'value',7],[],e,s,gg)
_(oVH,lYH)
_(cEE,oVH)
}
var aZH=_n('view')
_rz(z,aZH,'class',250,e,s,gg)
var t1H=_n('view')
_rz(z,t1H,'class',251,e,s,gg)
var e2H=_oz(z,252,e,s,gg)
_(t1H,e2H)
_(aZH,t1H)
var b3H=_mz(z,'view',['bindtap',253,'class',1,'data-event-opts',2],[],e,s,gg)
var o4H=_n('text')
_rz(z,o4H,'class',256,e,s,gg)
var x5H=_oz(z,257,e,s,gg)
_(o4H,x5H)
_(b3H,o4H)
_(aZH,b3H)
_(o8D,aZH)
var o6H=_n('view')
_rz(z,o6H,'class',258,e,s,gg)
var f7H=_n('view')
_rz(z,f7H,'class',259,e,s,gg)
var c8H=_oz(z,260,e,s,gg)
_(f7H,c8H)
_(o6H,f7H)
var h9H=_mz(z,'input',['bindinput',261,'class',1,'data-event-opts',2,'disabled',3,'placeholder',4,'value',5],[],e,s,gg)
_(o6H,h9H)
_(o8D,o6H)
var o0H=_n('view')
_rz(z,o0H,'class',267,e,s,gg)
var cAI=_n('view')
_rz(z,cAI,'class',268,e,s,gg)
var oBI=_oz(z,269,e,s,gg)
_(cAI,oBI)
_(o0H,cAI)
var lCI=_mz(z,'input',['adjustPosition',270,'bindinput',1,'class',2,'data-event-opts',3,'holdKeyboard',4,'placeholder',5,'type',6,'value',7],[],e,s,gg)
_(o0H,lCI)
_(o8D,o0H)
var aDI=_n('view')
_rz(z,aDI,'class',278,e,s,gg)
_(o8D,aDI)
x9D.wxXCkey=1
o0D.wxXCkey=1
fAE.wxXCkey=1
cBE.wxXCkey=1
hCE.wxXCkey=1
oDE.wxXCkey=1
cEE.wxXCkey=1
_(t5D,o8D)
var tEI=_n('view')
_rz(z,tEI,'class',279,e,s,gg)
var eFI=_n('view')
_rz(z,eFI,'class',280,e,s,gg)
var bGI=_mz(z,'checkbox-group',['bindchange',281,'class',1,'data-event-opts',2],[],e,s,gg)
var oHI=_n('label')
_rz(z,oHI,'class',284,e,s,gg)
var xII=_mz(z,'checkbox',['checked',285,'class',1,'color',2,'value',3],[],e,s,gg)
_(oHI,xII)
var oJI=_n('text')
_rz(z,oJI,'class',289,e,s,gg)
var fKI=_oz(z,290,e,s,gg)
_(oJI,fKI)
_(oHI,oJI)
var cLI=_mz(z,'text',['catchtap',291,'class',1,'data-event-opts',2],[],e,s,gg)
var hMI=_oz(z,294,e,s,gg)
_(cLI,hMI)
_(oHI,cLI)
_(bGI,oHI)
_(eFI,bGI)
_(tEI,eFI)
var oNI=_mz(z,'button',['bindtap',295,'class',1,'data-event-opts',2,'loading',3],[],e,s,gg)
var cOI=_oz(z,299,e,s,gg)
_(oNI,cOI)
_(tEI,oNI)
var oPI=_mz(z,'button',['bindtap',300,'class',1,'data-event-opts',2],[],e,s,gg)
var lQI=_oz(z,303,e,s,gg)
_(oPI,lQI)
_(tEI,oPI)
_(t5D,tEI)
var e6D=_v()
_(t5D,e6D)
if(_oz(z,304,e,s,gg)){e6D.wxVkey=1
var aRI=_mz(z,'view',['bindtap',305,'class',1,'data-event-opts',2],[],e,s,gg)
var tSI=_mz(z,'view',['catchtap',308,'class',1,'data-event-opts',2],[],e,s,gg)
var eTI=_n('view')
_rz(z,eTI,'class',311,e,s,gg)
var bUI=_n('text')
_rz(z,bUI,'class',312,e,s,gg)
var oVI=_oz(z,313,e,s,gg)
_(bUI,oVI)
_(eTI,bUI)
var xWI=_mz(z,'text',['bindtap',314,'class',1,'data-event-opts',2],[],e,s,gg)
var oXI=_oz(z,317,e,s,gg)
_(xWI,oXI)
_(eTI,xWI)
_(tSI,eTI)
var fYI=_mz(z,'scroll-view',['class',318,'scrollY',1,'showScrollbar',2],[],e,s,gg)
var cZI=_v()
_(fYI,cZI)
if(_oz(z,321,e,s,gg)){cZI.wxVkey=1
var h1I=_n('view')
_rz(z,h1I,'class',322,e,s,gg)
var o2I=_oz(z,323,e,s,gg)
_(h1I,o2I)
_(cZI,h1I)
}
var c3I=_v()
_(fYI,c3I)
var o4I=function(a6I,l5I,t7I,gg){
var b9I=_mz(z,'view',['bindtap',327,'class',1,'data-event-opts',2,'data-index',3],[],a6I,l5I,gg)
var o0I=_oz(z,331,a6I,l5I,gg)
_(b9I,o0I)
_(t7I,b9I)
return t7I
}
c3I.wxXCkey=2
_2z(z,326,o4I,e,s,gg,c3I,'item','idx','')
cZI.wxXCkey=1
_(tSI,fYI)
_(aRI,tSI)
_(e6D,aRI)
}
var b7D=_v()
_(t5D,b7D)
if(_oz(z,332,e,s,gg)){b7D.wxVkey=1
var xAJ=_mz(z,'view',['bindtap',333,'class',1,'data-event-opts',2],[],e,s,gg)
var oBJ=_mz(z,'view',['catchtap',336,'class',1,'data-event-opts',2,'style',3],[],e,s,gg)
var fCJ=_n('view')
_rz(z,fCJ,'class',340,e,s,gg)
var cDJ=_n('text')
_rz(z,cDJ,'class',341,e,s,gg)
var hEJ=_oz(z,342,e,s,gg)
_(cDJ,hEJ)
_(fCJ,cDJ)
var oFJ=_mz(z,'text',['bindtap',343,'class',1,'data-event-opts',2],[],e,s,gg)
var cGJ=_oz(z,346,e,s,gg)
_(oFJ,cGJ)
_(fCJ,oFJ)
_(oBJ,fCJ)
var oHJ=_mz(z,'input',['adjustPosition',347,'bindblur',1,'bindfocus',2,'bindinput',3,'class',4,'data-event-opts',5,'holdKeyboard',6,'placeholder',7,'value',8],[],e,s,gg)
_(oBJ,oHJ)
var lIJ=_mz(z,'scroll-view',['class',356,'scrollY',1,'showScrollbar',2,'style',3],[],e,s,gg)
var aJJ=_v()
_(lIJ,aJJ)
if(_oz(z,360,e,s,gg)){aJJ.wxVkey=1
var tKJ=_n('view')
_rz(z,tKJ,'class',361,e,s,gg)
var eLJ=_oz(z,362,e,s,gg)
_(tKJ,eLJ)
_(aJJ,tKJ)
}
else{aJJ.wxVkey=2
var bMJ=_v()
_(aJJ,bMJ)
if(_oz(z,363,e,s,gg)){bMJ.wxVkey=1
var oNJ=_n('view')
_rz(z,oNJ,'class',364,e,s,gg)
var xOJ=_oz(z,365,e,s,gg)
_(oNJ,xOJ)
_(bMJ,oNJ)
}
else{bMJ.wxVkey=2
var oPJ=_v()
_(bMJ,oPJ)
if(_oz(z,366,e,s,gg)){oPJ.wxVkey=1
var fQJ=_n('view')
_rz(z,fQJ,'class',367,e,s,gg)
var cRJ=_oz(z,368,e,s,gg)
_(fQJ,cRJ)
_(oPJ,fQJ)
}
oPJ.wxXCkey=1
}
bMJ.wxXCkey=1
}
var hSJ=_v()
_(lIJ,hSJ)
var oTJ=function(oVJ,cUJ,lWJ,gg){
var tYJ=_mz(z,'view',['bindtap',372,'class',1,'data-event-opts',2,'data-index',3],[],oVJ,cUJ,gg)
var eZJ=_oz(z,376,oVJ,cUJ,gg)
_(tYJ,eZJ)
_(lWJ,tYJ)
return lWJ
}
hSJ.wxXCkey=2
_2z(z,371,oTJ,e,s,gg,hSJ,'item','idx','')
aJJ.wxXCkey=1
_(oBJ,lIJ)
_(xAJ,oBJ)
_(b7D,xAJ)
}
var b1J=_mz(z,'privacy-auth-popup',['bind:__l',377,'class',1,'vueId',2],[],e,s,gg)
_(t5D,b1J)
e6D.wxXCkey=1
b7D.wxXCkey=1
_(r,t5D)
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx0_XC_3";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx0_XC_3();	if (__vd_version_info__.delayedGwx) __wxAppCode__['sub-pages/auth/register.wxml'] = [$gwx0_XC_3, './sub-pages/auth/register.wxml'];else __wxAppCode__['sub-pages/auth/register.wxml'] = $gwx0_XC_3( './sub-pages/auth/register.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['sub-pages/auth/register.wxss']=setCssToHead(["body{background:#f5f5f5;height:100%}\n.",[1],"page.",[1],"data-v-75ceecf4{background:#f5f5f5;bottom:0;box-sizing:border-box;left:0;position:fixed;right:0;top:0}\n.",[1],"label.",[1],"data-v-75ceecf4{color:#666;font-size:",[0,26],";margin-bottom:",[0,16],"}\n.",[1],"label.",[1],"required.",[1],"data-v-75ceecf4::before{color:#e53935;content:\x22*\x22;margin-right:",[0,6],"}\n.",[1],"scroll.",[1],"data-v-75ceecf4{-webkit-overflow-scrolling:touch;bottom:calc(",[0,290]," + env(safe-area-inset-bottom));box-sizing:border-box;left:0;overflow-y:auto;position:absolute;right:0;top:0}\n.",[1],"section.",[1],"data-v-75ceecf4{background:#fff;isolation:isolate;margin-bottom:",[0,16],";padding:",[0,24]," ",[0,28],";position:relative}\n.",[1],"input.",[1],"data-v-75ceecf4{box-sizing:border-box;color:#333;display:block;font-size:",[0,28],";height:auto;line-height:normal;min-height:",[0,72],";padding:",[0,18]," 0;width:100%}\n.",[1],"picker-val.",[1],"data-v-75ceecf4{-webkit-align-items:center;align-items:center;color:#333;display:-webkit-flex;display:flex;font-size:",[0,28],";min-height:",[0,72],"}\n.",[1],"placeholder.",[1],"data-v-75ceecf4{color:#999}\n.",[1],"bank-mask.",[1],"data-v-75ceecf4{-webkit-align-items:flex-end;align-items:flex-end;background:rgba(0,0,0,.35);bottom:0;display:-webkit-flex;display:flex;left:0;position:fixed;right:0;top:0;z-index:30}\n.",[1],"bank-panel.",[1],"data-v-75ceecf4{background:#fff;border-radius:",[0,20]," ",[0,20]," 0 0;box-sizing:border-box;padding:",[0,20],";transition:-webkit-transform .2s ease-out;transition:transform .2s ease-out;transition:transform .2s ease-out,-webkit-transform .2s ease-out;width:100%}\n.",[1],"bank-head.",[1],"data-v-75ceecf4{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:space-between;justify-content:space-between;margin-bottom:",[0,16],"}\n.",[1],"bank-title.",[1],"data-v-75ceecf4{color:#222;font-size:",[0,30],";font-weight:600}\n.",[1],"bank-close.",[1],"data-v-75ceecf4{color:#666;font-size:",[0,26],"}\n.",[1],"bank-search.",[1],"data-v-75ceecf4{border:",[0,1]," solid #e5e7eb;border-radius:",[0,10],";font-size:",[0,28],";height:",[0,72],";line-height:",[0,72],";margin-bottom:",[0,16],";padding:0 ",[0,20],"}\n.",[1],"bank-list.",[1],"data-v-75ceecf4{max-height:50vh}\n.",[1],"bank-item.",[1],"data-v-75ceecf4{-webkit-align-items:center;align-items:center;border-bottom:",[0,1]," solid #f0f0f0;color:#333;display:-webkit-flex;display:flex;font-size:",[0,28],";min-height:",[0,72],";padding:",[0,8]," ",[0,4],"}\n.",[1],"bank-empty.",[1],"data-v-75ceecf4{color:#999;font-size:",[0,24],";padding:",[0,24]," 0;text-align:center}\n.",[1],"upload-row.",[1],"data-v-75ceecf4{-webkit-align-items:flex-start;align-items:flex-start;display:-webkit-flex;display:flex}\n.",[1],"upload-btn.",[1],"data-v-75ceecf4{-webkit-align-items:center;align-items:center;background:#f9fbff;border:",[0,2]," dashed #d6deea;border-radius:",[0,12],";display:-webkit-flex;display:flex;height:",[0,220],";-webkit-justify-content:center;justify-content:center;width:",[0,220],"}\n.",[1],"upload-plus.",[1],"data-v-75ceecf4{color:#9aa3af;font-size:",[0,60],";line-height:1}\n.",[1],"upload-hint.",[1],"data-v-75ceecf4{color:#999;display:block;font-size:",[0,22],";margin-top:",[0,14],"}\n.",[1],"thumb-wrap.",[1],"data-v-75ceecf4{border-radius:",[0,12],";height:",[0,220],";overflow:hidden;position:relative;width:",[0,220],"}\n.",[1],"thumb.",[1],"data-v-75ceecf4{height:100%;width:100%}\n.",[1],"thumb-del.",[1],"data-v-75ceecf4{background:rgba(0,0,0,.45);bottom:0;color:#fff;font-size:",[0,22],";left:0;padding:",[0,8]," 0;position:absolute;right:0;text-align:center}\n.",[1],"foot-space.",[1],"data-v-75ceecf4{height:60vh}\n.",[1],"bottom-bar.",[1],"data-v-75ceecf4{background:#fff;border-top:",[0,1]," solid #eee;bottom:0;box-sizing:border-box;left:0;padding:",[0,12]," ",[0,24]," calc(",[0,16]," + env(safe-area-inset-bottom));position:fixed;right:0;z-index:10}\n.",[1],"privacy-wrap.",[1],"data-v-75ceecf4{margin-bottom:",[0,12],"}\n.",[1],"privacy-label.",[1],"data-v-75ceecf4{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;-webkit-flex-wrap:wrap;flex-wrap:wrap}\n.",[1],"privacy-text.",[1],"data-v-75ceecf4{color:#666;font-size:",[0,24],";margin-left:",[0,8],"}\n.",[1],"privacy-link.",[1],"data-v-75ceecf4{color:#4ab83a;font-size:",[0,24],"}\n.",[1],"btn-submit.",[1],"data-v-75ceecf4{background:linear-gradient(180deg,#5dcc45,#4ab83a);border:none;border-radius:",[0,12],";color:#fff;font-size:",[0,30],";height:",[0,88],";line-height:",[0,88],";width:100%}\n.",[1],"btn-back.",[1],"data-v-75ceecf4{background:#f5f5f5;border-radius:",[0,12],";color:#666;font-size:",[0,28],";height:",[0,80],";line-height:",[0,80],";margin-top:",[0,14],";width:100%}\n.",[1],"btn-back.",[1],"data-v-75ceecf4::after,.",[1],"btn-submit.",[1],"data-v-75ceecf4::after{border:none}\n",],"Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./sub-pages/auth/register.wxss:1:1)",{path:"./sub-pages/auth/register.wxss"});
}