$gwx0_XC_0=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx0_XC_0 || [];
function gz$gwx0_XC_0_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx0_XC_0_1)return __WXML_GLOBAL__.ops_cached.$gwx0_XC_0_1
__WXML_GLOBAL__.ops_cached.$gwx0_XC_0_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'login-box data-v-7b0f3a30'])
Z([3,'login-title data-v-7b0f3a30'])
Z([3,'骑手登录'])
Z([3,'logo data-v-7b0f3a30'])
Z([3,'data-v-7b0f3a30'])
Z([3,'aspectFit'])
Z([3,'/sub-pages/auth/static/login/logo.png'])
Z([3,'desc data-v-7b0f3a30'])
Z(z[4])
Z([3,'/sub-pages/auth/static/login/desc.png'])
Z([3,'form data-v-7b0f3a30'])
Z([3,'form_item data-v-7b0f3a30'])
Z([3,'img1 data-v-7b0f3a30'])
Z([3,'/sub-pages/auth/static/login/phone.png'])
Z([3,'__e'])
Z([3,'inp1 data-v-7b0f3a30'])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[5],[[4],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'']],[1,'phone']],[1,'$event']],[[4],[[5]]]]]]]],[[4],[[5],[[5],[1,'onInput']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([3,'请输入手机号码'])
Z([3,'pl'])
Z([3,'number'])
Z([[7],[3,'phone']])
Z(z[11])
Z(z[12])
Z([3,'/sub-pages/auth/static/login/password.png'])
Z(z[14])
Z(z[15])
Z([[4],[[5],[[4],[[5],[[5],[1,'input']],[[4],[[5],[[4],[[5],[[5],[1,'__set_model']],[[4],[[5],[[5],[[5],[[5],[1,'']],[1,'password']],[1,'$event']],[[4],[[5]]]]]]]]]]]]])
Z([3,'true'])
Z([3,'请输入密码'])
Z(z[18])
Z([3,'text'])
Z([[7],[3,'password']])
Z([3,'privacy-wrap data-v-7b0f3a30'])
Z(z[14])
Z(z[4])
Z([[4],[[5],[[4],[[5],[[5],[1,'change']],[[4],[[5],[[4],[[5],[[5],[1,'onPrivacyCheckboxChange']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([3,'privacy-label data-v-7b0f3a30'])
Z([[7],[3,'agreePrivacy']])
Z(z[4])
Z([3,'#3662DD'])
Z([3,'1'])
Z([3,'privacy-text data-v-7b0f3a30'])
Z([3,'我已阅读并同意'])
Z(z[14])
Z([3,'privacy-link data-v-7b0f3a30'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'openPrivacyPolicy']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([3,'《隐私政策》'])
Z(z[4])
Z([3,'padding-top:76rpx;'])
Z(z[14])
Z([3,'btn data-v-7b0f3a30'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[1,'userLogin']]]]]]]]])
Z([3,'登录'])
Z(z[14])
Z(z[50])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'goBack']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([3,'返回'])
Z([[2,'!'],[[6],[[7],[3,'puserInfo']],[3,'phone']]])
Z(z[14])
Z([3,'other-login data-v-7b0f3a30'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[1,'getUserProfile']]]]]]]]])
Z([3,'ol-tilte data-v-7b0f3a30'])
Z(z[4])
Z([3,'授权登录'])
Z([3,'wx-login _div data-v-7b0f3a30'])
Z(z[4])
Z(z[5])
Z([3,'/sub-pages/auth/static/login/weixin_icon.png'])
Z(z[14])
Z(z[59])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[1,'fakeLogin']]]]]]]]])
Z(z[61])
Z(z[4])
Z([3,'一键登录'])
Z(z[64])
Z(z[4])
Z(z[5])
Z(z[67])
Z([3,'bottom_img data-v-7b0f3a30'])
Z([3,'widthFix'])
Z([3,'/sub-pages/auth/static/login/bottom_img.png'])
Z([3,'popup-box data-v-7b0f3a30'])
Z([[2,'!'],[[7],[3,'showPopup']]])
Z([3,'login-popup data-v-7b0f3a30'])
Z([3,'lp-top data-v-7b0f3a30'])
Z([3,'lpt-left data-v-7b0f3a30'])
Z([3,'title data-v-7b0f3a30'])
Z(z[4])
Z(z[52])
Z([3,'tips data-v-7b0f3a30'])
Z(z[4])
Z([3,'登录即可解锁更多权益'])
Z(z[14])
Z([3,'lpt-right data-v-7b0f3a30'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'e0']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z(z[4])
Z([3,'aspectFill'])
Z([3,'/sub-pages/auth/static/login/close_icon.png'])
Z([3,'lp-center data-v-7b0f3a30'])
Z(z[86])
Z([3,'申请获取以下权限'])
Z(z[89])
Z([3,'获得你的公开信息（昵称、头像等）'])
Z(z[89])
Z([3,'获得你的手机号码'])
Z([3,'lp-bottom data-v-7b0f3a30'])
Z(z[14])
Z([3,'option-btn data-v-7b0f3a30'])
Z([[4],[[5],[[4],[[5],[[5],[1,'getphonenumber']],[[4],[[5],[[4],[[5],[[5],[1,'getPhoneNumber']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([3,'getPhoneNumber'])
Z([3,'获取手机号'])
Z([3,'__l'])
Z(z[4])
Z([3,'e6d709c4-1'])
})(__WXML_GLOBAL__.ops_cached.$gwx0_XC_0_1);return __WXML_GLOBAL__.ops_cached.$gwx0_XC_0_1
}
__WXML_GLOBAL__.ops_set.$gwx0_XC_0=z;
__WXML_GLOBAL__.ops_init.$gwx0_XC_0=true;
var x=['./sub-pages/auth/login.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx0_XC_0_1()
var oB=_n('view')
_rz(z,oB,'class',0,e,s,gg)
var oD=_n('view')
_rz(z,oD,'class',1,e,s,gg)
var fE=_oz(z,2,e,s,gg)
_(oD,fE)
_(oB,oD)
var cF=_n('view')
_rz(z,cF,'class',3,e,s,gg)
var hG=_mz(z,'image',['class',4,'mode',1,'src',2],[],e,s,gg)
_(cF,hG)
_(oB,cF)
var oH=_n('view')
_rz(z,oH,'class',7,e,s,gg)
var cI=_mz(z,'image',['class',8,'src',1],[],e,s,gg)
_(oH,cI)
_(oB,oH)
var oJ=_n('view')
_rz(z,oJ,'class',10,e,s,gg)
var lK=_n('view')
_rz(z,lK,'class',11,e,s,gg)
var aL=_mz(z,'image',['class',12,'src',1],[],e,s,gg)
_(lK,aL)
var tM=_mz(z,'input',['bindinput',14,'class',1,'data-event-opts',2,'placeholder',3,'placeholderClass',4,'type',5,'value',6],[],e,s,gg)
_(lK,tM)
_(oJ,lK)
var eN=_n('view')
_rz(z,eN,'class',21,e,s,gg)
var bO=_mz(z,'image',['class',22,'src',1],[],e,s,gg)
_(eN,bO)
var oP=_mz(z,'input',['bindinput',24,'class',1,'data-event-opts',2,'password',3,'placeholder',4,'placeholderClass',5,'type',6,'value',7],[],e,s,gg)
_(eN,oP)
_(oJ,eN)
_(oB,oJ)
var xQ=_n('view')
_rz(z,xQ,'class',32,e,s,gg)
var oR=_mz(z,'checkbox-group',['bindchange',33,'class',1,'data-event-opts',2],[],e,s,gg)
var fS=_n('label')
_rz(z,fS,'class',36,e,s,gg)
var cT=_mz(z,'checkbox',['checked',37,'class',1,'color',2,'value',3],[],e,s,gg)
_(fS,cT)
var hU=_n('text')
_rz(z,hU,'class',41,e,s,gg)
var oV=_oz(z,42,e,s,gg)
_(hU,oV)
_(fS,hU)
var cW=_mz(z,'text',['catchtap',43,'class',1,'data-event-opts',2],[],e,s,gg)
var oX=_oz(z,46,e,s,gg)
_(cW,oX)
_(fS,cW)
_(oR,fS)
_(xQ,oR)
_(oB,xQ)
var lY=_mz(z,'view',['class',47,'style',1],[],e,s,gg)
var aZ=_mz(z,'button',['bindtap',49,'class',1,'data-event-opts',2],[],e,s,gg)
var t1=_oz(z,52,e,s,gg)
_(aZ,t1)
_(lY,aZ)
var e2=_mz(z,'button',['bindtap',53,'class',1,'data-event-opts',2],[],e,s,gg)
var b3=_oz(z,56,e,s,gg)
_(e2,b3)
_(lY,e2)
_(oB,lY)
var xC=_v()
_(oB,xC)
if(_oz(z,57,e,s,gg)){xC.wxVkey=1
var o4=_mz(z,'view',['bindtap',58,'class',1,'data-event-opts',2],[],e,s,gg)
var x5=_n('view')
_rz(z,x5,'class',61,e,s,gg)
var o6=_n('text')
_rz(z,o6,'class',62,e,s,gg)
var f7=_oz(z,63,e,s,gg)
_(o6,f7)
_(x5,o6)
_(o4,x5)
var c8=_n('view')
_rz(z,c8,'class',64,e,s,gg)
var h9=_mz(z,'image',['class',65,'mode',1,'src',2],[],e,s,gg)
_(c8,h9)
_(o4,c8)
_(xC,o4)
}
else{xC.wxVkey=2
var o0=_mz(z,'view',['bindtap',68,'class',1,'data-event-opts',2],[],e,s,gg)
var cAB=_n('view')
_rz(z,cAB,'class',71,e,s,gg)
var oBB=_n('text')
_rz(z,oBB,'class',72,e,s,gg)
var lCB=_oz(z,73,e,s,gg)
_(oBB,lCB)
_(cAB,oBB)
_(o0,cAB)
var aDB=_n('view')
_rz(z,aDB,'class',74,e,s,gg)
var tEB=_mz(z,'image',['class',75,'mode',1,'src',2],[],e,s,gg)
_(aDB,tEB)
_(o0,aDB)
_(xC,o0)
}
var eFB=_mz(z,'image',['class',78,'mode',1,'src',2],[],e,s,gg)
_(oB,eFB)
var bGB=_mz(z,'view',['class',81,'hidden',1],[],e,s,gg)
var oHB=_n('view')
_rz(z,oHB,'class',83,e,s,gg)
var xIB=_n('view')
_rz(z,xIB,'class',84,e,s,gg)
var oJB=_n('view')
_rz(z,oJB,'class',85,e,s,gg)
var fKB=_n('view')
_rz(z,fKB,'class',86,e,s,gg)
var cLB=_n('text')
_rz(z,cLB,'class',87,e,s,gg)
var hMB=_oz(z,88,e,s,gg)
_(cLB,hMB)
_(fKB,cLB)
_(oJB,fKB)
var oNB=_n('view')
_rz(z,oNB,'class',89,e,s,gg)
var cOB=_n('text')
_rz(z,cOB,'class',90,e,s,gg)
var oPB=_oz(z,91,e,s,gg)
_(cOB,oPB)
_(oNB,cOB)
_(oJB,oNB)
_(xIB,oJB)
var lQB=_mz(z,'view',['bindtap',92,'class',1,'data-event-opts',2],[],e,s,gg)
var aRB=_mz(z,'image',['class',95,'mode',1,'src',2],[],e,s,gg)
_(lQB,aRB)
_(xIB,lQB)
_(oHB,xIB)
var tSB=_n('view')
_rz(z,tSB,'class',98,e,s,gg)
var eTB=_n('view')
_rz(z,eTB,'class',99,e,s,gg)
var bUB=_oz(z,100,e,s,gg)
_(eTB,bUB)
_(tSB,eTB)
var oVB=_n('view')
_rz(z,oVB,'class',101,e,s,gg)
var xWB=_oz(z,102,e,s,gg)
_(oVB,xWB)
_(tSB,oVB)
var oXB=_n('view')
_rz(z,oXB,'class',103,e,s,gg)
var fYB=_oz(z,104,e,s,gg)
_(oXB,fYB)
_(tSB,oXB)
_(oHB,tSB)
var cZB=_n('view')
_rz(z,cZB,'class',105,e,s,gg)
var h1B=_mz(z,'button',['bindgetphonenumber',106,'class',1,'data-event-opts',2,'openType',3],[],e,s,gg)
var o2B=_oz(z,110,e,s,gg)
_(h1B,o2B)
_(cZB,h1B)
_(oHB,cZB)
_(bGB,oHB)
_(oB,bGB)
var c3B=_mz(z,'privacy-auth-popup',['bind:__l',111,'class',1,'vueId',2],[],e,s,gg)
_(oB,c3B)
xC.wxXCkey=1
_(r,oB)
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx0_XC_0";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx0_XC_0();	if (__vd_version_info__.delayedGwx) __wxAppCode__['sub-pages/auth/login.wxml'] = [$gwx0_XC_0, './sub-pages/auth/login.wxml'];else __wxAppCode__['sub-pages/auth/login.wxml'] = $gwx0_XC_0( './sub-pages/auth/login.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['sub-pages/auth/login.wxss']=setCssToHead([".",[1],"login-box.",[1],"data-v-7b0f3a30{height:100vh;position:relative;width:100vw}\n.",[1],"login-title.",[1],"data-v-7b0f3a30{color:#333;font-size:",[0,36],";font-weight:700;padding-top:",[0,74],";text-align:center}\n.",[1],"logo.",[1],"data-v-7b0f3a30{padding-top:",[0,72],";text-align:center}\n.",[1],"logo wx-image.",[1],"data-v-7b0f3a30{height:",[0,172],";width:",[0,172],"}\n.",[1],"desc.",[1],"data-v-7b0f3a30{padding-top:",[0,48],";text-align:center}\n.",[1],"desc wx-image.",[1],"data-v-7b0f3a30{height:",[0,46],";width:",[0,284],"}\n.",[1],"form.",[1],"data-v-7b0f3a30{margin:0 auto;padding-top:",[0,32],";width:",[0,618],"}\n.",[1],"form .",[1],"form_item.",[1],"data-v-7b0f3a30{border-bottom:",[0,2]," solid #efefef;height:",[0,100],";position:relative}\n.",[1],"form .",[1],"img1.",[1],"data-v-7b0f3a30{bottom:",[0,28],";height:",[0,40],";left:",[0,26],";position:absolute;width:",[0,36],"}\n.",[1],"form .",[1],"inp1.",[1],"data-v-7b0f3a30{bottom:0;display:inline-block;font-size:",[0,30],";height:",[0,98],";left:",[0,96],";line-height:",[0,98],";position:absolute;width:",[0,524],"}\n.",[1],"form .",[1],"pl.",[1],"data-v-7b0f3a30{color:#bbb;font-size:",[0,30],"}\n.",[1],"privacy-wrap.",[1],"data-v-7b0f3a30{margin:",[0,24]," auto 0;width:",[0,618],"}\n.",[1],"privacy-label.",[1],"data-v-7b0f3a30{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;-webkit-flex-wrap:wrap;flex-wrap:wrap}\n.",[1],"privacy-text.",[1],"data-v-7b0f3a30{color:#666;font-size:",[0,24],";margin-left:",[0,8],"}\n.",[1],"privacy-link.",[1],"data-v-7b0f3a30{color:#3662dd;font-size:",[0,24],"}\n.",[1],"btn.",[1],"data-v-7b0f3a30{background:linear-gradient(90deg,#5095f4,#3662dd);border-radius:",[0,8],";color:#fff;font-size:",[0,32],";height:",[0,96],";line-height:",[0,96],";margin:0 auto;width:",[0,640],"}\n.",[1],"btn + .",[1],"btn.",[1],"data-v-7b0f3a30{margin-top:",[0,20],"}\n.",[1],"other-login.",[1],"data-v-7b0f3a30{margin:",[0,80]," auto 0;position:relative;width:",[0,618],";z-index:5}\n.",[1],"other-login .",[1],"ol-tilte.",[1],"data-v-7b0f3a30{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;-webkit-justify-content:center;justify-content:center}\n.",[1],"other-login .",[1],"ol-tilte.",[1],"data-v-7b0f3a30:after,.",[1],"other-login .",[1],"ol-tilte.",[1],"data-v-7b0f3a30:before{border-bottom:",[0,2]," solid #efefef;content:\x22\x22;display:block;width:30%}\n.",[1],"other-login .",[1],"ol-tilte wx-text.",[1],"data-v-7b0f3a30{color:#666;font-size:",[0,26],";padding:0 ",[0,20],"}\n.",[1],"other-login .",[1],"wx-login.",[1],"data-v-7b0f3a30{height:",[0,88],";margin:",[0,40]," auto 0;width:",[0,88],"}\n.",[1],"other-login .",[1],"wx-login wx-image.",[1],"data-v-7b0f3a30{display:block;height:100%;width:100%}\n.",[1],"bottom_img.",[1],"data-v-7b0f3a30{bottom:0;display:block;left:0;position:absolute;width:100%}\n.",[1],"popup-box.",[1],"data-v-7b0f3a30{background-color:rgba(0,0,0,.5);height:100%;left:0;position:absolute;top:0;width:100%;z-index:10}\n.",[1],"login-popup.",[1],"data-v-7b0f3a30{background-color:#fff;bottom:0;left:0;padding-bottom:",[0,40],";position:absolute;width:100%;z-index:10}\n.",[1],"login-popup .",[1],"lp-top.",[1],"data-v-7b0f3a30{-webkit-align-items:center;align-items:center;color:#000;display:-webkit-flex;display:flex;line-height:1.2}\n.",[1],"login-popup .",[1],"lp-top .",[1],"lpt-left.",[1],"data-v-7b0f3a30{-webkit-flex:1;flex:1;padding:",[0,30],"}\n.",[1],"login-popup .",[1],"lp-top .",[1],"lpt-left .",[1],"title.",[1],"data-v-7b0f3a30{font-size:",[0,28],";font-weight:500}\n.",[1],"login-popup .",[1],"lp-top .",[1],"lpt-left .",[1],"tips.",[1],"data-v-7b0f3a30{color:#9a9b9b;font-size:",[0,18],";margin-top:",[0,10],"}\n.",[1],"login-popup .",[1],"lp-top .",[1],"lpt-right.",[1],"data-v-7b0f3a30{padding:",[0,30],"}\n.",[1],"login-popup .",[1],"lp-top .",[1],"lpt-right wx-image.",[1],"data-v-7b0f3a30{display:block;height:",[0,28],";width:",[0,28],"}\n.",[1],"login-popup .",[1],"lp-center.",[1],"data-v-7b0f3a30{color:#000;padding:",[0,10]," ",[0,30]," ",[0,40],";position:relative}\n.",[1],"login-popup .",[1],"lp-center.",[1],"data-v-7b0f3a30:after{border-bottom:",[0,1]," solid #ededed;bottom:0;content:\x22\x22;left:",[0,30],";position:absolute;right:",[0,30],"}\n.",[1],"login-popup .",[1],"lp-center .",[1],"title.",[1],"data-v-7b0f3a30{font-size:",[0,28],";font-weight:600}\n.",[1],"login-popup .",[1],"lp-center .",[1],"tips.",[1],"data-v-7b0f3a30{font-size:",[0,26],";margin-top:",[0,10],"}\n.",[1],"login-popup .",[1],"lp-bottom.",[1],"data-v-7b0f3a30{margin-top:",[0,40],";padding:0 ",[0,30],"}\n.",[1],"login-popup .",[1],"lp-bottom .",[1],"option-btn.",[1],"data-v-7b0f3a30{background:linear-gradient(90deg,#5095f4,#3662dd);color:#fff;font-size:",[0,22],";height:",[0,86],";line-height:",[0,86],";padding:0 ",[0,30],";text-align:center}\n",],"Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./sub-pages/auth/login.wxss:1:2997)",{path:"./sub-pages/auth/login.wxss"});
}