$gwx0_XC_36=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx0_XC_36 || [];
function gz$gwx0_XC_36_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx0_XC_36_1)return __WXML_GLOBAL__.ops_cached.$gwx0_XC_36_1
__WXML_GLOBAL__.ops_cached.$gwx0_XC_36_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'__l'])
Z([3,'data-v-67dd3a90'])
Z([3,'7251d169-1'])
Z([[4],[[5],[1,'default']]])
Z([3,'detail-page p-20 data-v-67dd3a90'])
Z([3,'detail-card mb-20 data-v-67dd3a90'])
Z([3,'detail-card__head data-v-67dd3a90'])
Z([3,'detail-card__title data-v-67dd3a90'])
Z([a,[[2,'||'],[[6],[[7],[3,'detail']],[3,'title']],[1,'--']]])
Z(z[0])
Z(z[1])
Z([1,true])
Z([[2,'?:'],[[2,'==='],[[6],[[7],[3,'detail']],[3,'status']],[[6],[[7],[3,'ISSUE_FEEDBACK_STATUS']],[3,'FINISHED']]],[1,'success'],[1,'warning']])
Z([[2,'+'],[[2,'+'],[1,'7251d169-2'],[1,',']],[1,'7251d169-1']])
Z(z[3])
Z([a,[[2,'+'],[[2,'+'],[1,''],[[6],[[7],[3,'$root']],[3,'m0']]],[1,'']]])
Z([3,'detail-grid data-v-67dd3a90'])
Z([3,'detail-grid__item data-v-67dd3a90'])
Z([3,'detail-grid__label data-v-67dd3a90'])
Z([3,'反馈编号'])
Z([3,'detail-grid__value-row data-v-67dd3a90'])
Z([3,'detail-grid__value data-v-67dd3a90'])
Z([a,[[2,'||'],[[6],[[7],[3,'detail']],[3,'feedbackNo']],[1,'--']]])
Z([[6],[[7],[3,'detail']],[3,'feedbackNo']])
Z([3,'__e'])
Z([3,'copy-btn data-v-67dd3a90'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[[5],[1,'handleCopy']],[[4],[[5],[1,'$0']]]],[[4],[[5],[1,'detail.feedbackNo']]]]]]]]]]])
Z(z[0])
Z(z[1])
Z([3,'var(--color-content)'])
Z([3,'copy'])
Z([3,'12'])
Z([[2,'+'],[[2,'+'],[1,'7251d169-3'],[1,',']],[1,'7251d169-1']])
Z(z[17])
Z(z[18])
Z([3,'问题类型'])
Z(z[21])
Z([a,[[2,'||'],[[6],[[7],[3,'detail']],[3,'feedbackTypeName']],[1,'--']]])
Z(z[17])
Z(z[18])
Z([3,'关联总仓'])
Z(z[21])
Z([a,[[2,'||'],[[6],[[7],[3,'detail']],[3,'regionWhName']],[1,'--']]])
Z([[6],[[7],[3,'detail']],[3,'orderCode']])
Z(z[17])
Z(z[18])
Z([3,'订单号'])
Z(z[21])
Z([a,[[6],[[7],[3,'detail']],[3,'orderCode']]])
Z(z[17])
Z(z[18])
Z([3,'反馈方式'])
Z(z[21])
Z([a,[[2,'?:'],[[2,'==='],[[6],[[7],[3,'detail']],[3,'anonymousFlag']],[1,1]],[1,'匿名反馈'],[1,'实名反馈']]])
Z(z[17])
Z(z[18])
Z([3,'提交时间'])
Z(z[21])
Z([a,[[6],[[7],[3,'$root']],[3,'m1']]])
Z(z[5])
Z([3,'detail-card__section data-v-67dd3a90'])
Z([3,'问题描述'])
Z([[4],[[5],[[5],[[5],[1,'detail-card__content']],[1,'data-v-67dd3a90']],[[2,'?:'],[[2,'&&'],[[7],[3,'showContentToggle']],[[2,'!'],[[7],[3,'contentExpanded']]]],[1,'detail-card__content--collapsed'],[1,'']]]])
Z([a,[[2,'+'],[[2,'+'],[1,''],[[2,'||'],[[6],[[7],[3,'detail']],[3,'content']],[1,'--']]],[1,'']]])
Z([[7],[3,'showContentToggle']])
Z(z[24])
Z([3,'content-toggle data-v-67dd3a90'])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'handleToggleContent']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([a,[[2,'+'],[[2,'+'],[1,''],[[2,'?:'],[[7],[3,'contentExpanded']],[1,'收起'],[1,'展开']]],[1,'']]])
Z([[6],[[7],[3,'detail']],[3,'finishContent']])
Z(z[5])
Z(z[60])
Z([3,'处理结果'])
Z([3,'detail-card__content data-v-67dd3a90'])
Z([a,[[6],[[7],[3,'detail']],[3,'finishContent']]])
Z([[6],[[7],[3,'$root']],[3,'g0']])
Z(z[5])
Z(z[60])
Z([3,'附件'])
Z(z[0])
Z(z[1])
Z([[7],[3,'attachmentList']])
Z([[6],[[7],[3,'uploadConfig']],[3,'height']])
Z(z[11])
Z([[2,'+'],[[2,'+'],[1,'7251d169-4'],[1,',']],[1,'7251d169-1']])
Z([[6],[[7],[3,'uploadConfig']],[3,'width']])
Z([3,'detail-card data-v-67dd3a90'])
Z(z[60])
Z([3,'处理记录'])
Z([[6],[[7],[3,'$root']],[3,'g1']])
Z([3,'timeline data-v-67dd3a90'])
Z([3,'__i0__'])
Z([3,'item'])
Z([[6],[[7],[3,'$root']],[3,'l0']])
Z([3,'id'])
Z([3,'timeline__item data-v-67dd3a90'])
Z([3,'timeline__dot data-v-67dd3a90'])
Z([3,'timeline__content data-v-67dd3a90'])
Z([3,'timeline__head data-v-67dd3a90'])
Z([3,'timeline__title data-v-67dd3a90'])
Z([a,[[2,'||'],[[6],[[6],[[7],[3,'item']],[3,'$orig']],[3,'actionTypeName']],[1,'状态更新']]])
Z([3,'timeline__time data-v-67dd3a90'])
Z([a,[[6],[[7],[3,'item']],[3,'m2']]])
Z([3,'empty-tip data-v-67dd3a90'])
Z([3,'暂无处理记录'])
})(__WXML_GLOBAL__.ops_cached.$gwx0_XC_36_1);return __WXML_GLOBAL__.ops_cached.$gwx0_XC_36_1
}
__WXML_GLOBAL__.ops_set.$gwx0_XC_36=z;
__WXML_GLOBAL__.ops_init.$gwx0_XC_36=true;
var x=['./package-system/issueFeedback/detail.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx0_XC_36_1()
var oZ9=_mz(z,'b-container',['bind:__l',0,'class',1,'vueId',1,'vueSlots',2],[],e,s,gg)
var f19=_n('view')
_rz(z,f19,'class',4,e,s,gg)
var o49=_n('view')
_rz(z,o49,'class',5,e,s,gg)
var c59=_n('view')
_rz(z,c59,'class',6,e,s,gg)
var o69=_n('view')
_rz(z,o69,'class',7,e,s,gg)
var l79=_oz(z,8,e,s,gg)
_(o69,l79)
_(c59,o69)
var a89=_mz(z,'b-tag',['bind:__l',9,'class',1,'plain',2,'type',3,'vueId',4,'vueSlots',5],[],e,s,gg)
var t99=_oz(z,15,e,s,gg)
_(a89,t99)
_(c59,a89)
_(o49,c59)
var e09=_n('view')
_rz(z,e09,'class',16,e,s,gg)
var oB0=_n('view')
_rz(z,oB0,'class',17,e,s,gg)
var xC0=_n('text')
_rz(z,xC0,'class',18,e,s,gg)
var oD0=_oz(z,19,e,s,gg)
_(xC0,oD0)
_(oB0,xC0)
var fE0=_n('view')
_rz(z,fE0,'class',20,e,s,gg)
var hG0=_n('text')
_rz(z,hG0,'class',21,e,s,gg)
var oH0=_oz(z,22,e,s,gg)
_(hG0,oH0)
_(fE0,hG0)
var cF0=_v()
_(fE0,cF0)
if(_oz(z,23,e,s,gg)){cF0.wxVkey=1
var cI0=_mz(z,'view',['catchtap',24,'class',1,'data-event-opts',2],[],e,s,gg)
var oJ0=_mz(z,'b-icon',['bind:__l',27,'class',1,'color',2,'name',3,'size',4,'vueId',5],[],e,s,gg)
_(cI0,oJ0)
_(cF0,cI0)
}
cF0.wxXCkey=1
cF0.wxXCkey=3
_(oB0,fE0)
_(e09,oB0)
var lK0=_n('view')
_rz(z,lK0,'class',33,e,s,gg)
var aL0=_n('text')
_rz(z,aL0,'class',34,e,s,gg)
var tM0=_oz(z,35,e,s,gg)
_(aL0,tM0)
_(lK0,aL0)
var eN0=_n('text')
_rz(z,eN0,'class',36,e,s,gg)
var bO0=_oz(z,37,e,s,gg)
_(eN0,bO0)
_(lK0,eN0)
_(e09,lK0)
var oP0=_n('view')
_rz(z,oP0,'class',38,e,s,gg)
var xQ0=_n('text')
_rz(z,xQ0,'class',39,e,s,gg)
var oR0=_oz(z,40,e,s,gg)
_(xQ0,oR0)
_(oP0,xQ0)
var fS0=_n('text')
_rz(z,fS0,'class',41,e,s,gg)
var cT0=_oz(z,42,e,s,gg)
_(fS0,cT0)
_(oP0,fS0)
_(e09,oP0)
var bA0=_v()
_(e09,bA0)
if(_oz(z,43,e,s,gg)){bA0.wxVkey=1
var hU0=_n('view')
_rz(z,hU0,'class',44,e,s,gg)
var oV0=_n('text')
_rz(z,oV0,'class',45,e,s,gg)
var cW0=_oz(z,46,e,s,gg)
_(oV0,cW0)
_(hU0,oV0)
var oX0=_n('text')
_rz(z,oX0,'class',47,e,s,gg)
var lY0=_oz(z,48,e,s,gg)
_(oX0,lY0)
_(hU0,oX0)
_(bA0,hU0)
}
var aZ0=_n('view')
_rz(z,aZ0,'class',49,e,s,gg)
var t10=_n('text')
_rz(z,t10,'class',50,e,s,gg)
var e20=_oz(z,51,e,s,gg)
_(t10,e20)
_(aZ0,t10)
var b30=_n('text')
_rz(z,b30,'class',52,e,s,gg)
var o40=_oz(z,53,e,s,gg)
_(b30,o40)
_(aZ0,b30)
_(e09,aZ0)
var x50=_n('view')
_rz(z,x50,'class',54,e,s,gg)
var o60=_n('text')
_rz(z,o60,'class',55,e,s,gg)
var f70=_oz(z,56,e,s,gg)
_(o60,f70)
_(x50,o60)
var c80=_n('text')
_rz(z,c80,'class',57,e,s,gg)
var h90=_oz(z,58,e,s,gg)
_(c80,h90)
_(x50,c80)
_(e09,x50)
bA0.wxXCkey=1
_(o49,e09)
_(f19,o49)
var o00=_n('view')
_rz(z,o00,'class',59,e,s,gg)
var oBAB=_n('view')
_rz(z,oBAB,'class',60,e,s,gg)
var lCAB=_oz(z,61,e,s,gg)
_(oBAB,lCAB)
_(o00,oBAB)
var aDAB=_n('view')
_rz(z,aDAB,'class',62,e,s,gg)
var tEAB=_oz(z,63,e,s,gg)
_(aDAB,tEAB)
_(o00,aDAB)
var cAAB=_v()
_(o00,cAAB)
if(_oz(z,64,e,s,gg)){cAAB.wxVkey=1
var eFAB=_mz(z,'view',['bindtap',65,'class',1,'data-event-opts',2],[],e,s,gg)
var bGAB=_oz(z,68,e,s,gg)
_(eFAB,bGAB)
_(cAAB,eFAB)
}
cAAB.wxXCkey=1
_(f19,o00)
var c29=_v()
_(f19,c29)
if(_oz(z,69,e,s,gg)){c29.wxVkey=1
var oHAB=_n('view')
_rz(z,oHAB,'class',70,e,s,gg)
var xIAB=_n('view')
_rz(z,xIAB,'class',71,e,s,gg)
var oJAB=_oz(z,72,e,s,gg)
_(xIAB,oJAB)
_(oHAB,xIAB)
var fKAB=_n('view')
_rz(z,fKAB,'class',73,e,s,gg)
var cLAB=_oz(z,74,e,s,gg)
_(fKAB,cLAB)
_(oHAB,fKAB)
_(c29,oHAB)
}
var h39=_v()
_(f19,h39)
if(_oz(z,75,e,s,gg)){h39.wxVkey=1
var hMAB=_n('view')
_rz(z,hMAB,'class',76,e,s,gg)
var oNAB=_n('view')
_rz(z,oNAB,'class',77,e,s,gg)
var cOAB=_oz(z,78,e,s,gg)
_(oNAB,cOAB)
_(hMAB,oNAB)
var oPAB=_mz(z,'b-upload',['bind:__l',79,'class',1,'fileList',2,'height',3,'readonly',4,'vueId',5,'width',6],[],e,s,gg)
_(hMAB,oPAB)
_(h39,hMAB)
}
var lQAB=_n('view')
_rz(z,lQAB,'class',86,e,s,gg)
var tSAB=_n('view')
_rz(z,tSAB,'class',87,e,s,gg)
var eTAB=_oz(z,88,e,s,gg)
_(tSAB,eTAB)
_(lQAB,tSAB)
var aRAB=_v()
_(lQAB,aRAB)
if(_oz(z,89,e,s,gg)){aRAB.wxVkey=1
var bUAB=_n('view')
_rz(z,bUAB,'class',90,e,s,gg)
var oVAB=_v()
_(bUAB,oVAB)
var xWAB=function(fYAB,oXAB,cZAB,gg){
var o2AB=_n('view')
_rz(z,o2AB,'class',95,fYAB,oXAB,gg)
var c3AB=_n('view')
_rz(z,c3AB,'class',96,fYAB,oXAB,gg)
_(o2AB,c3AB)
var o4AB=_n('view')
_rz(z,o4AB,'class',97,fYAB,oXAB,gg)
var l5AB=_n('view')
_rz(z,l5AB,'class',98,fYAB,oXAB,gg)
var a6AB=_n('text')
_rz(z,a6AB,'class',99,fYAB,oXAB,gg)
var t7AB=_oz(z,100,fYAB,oXAB,gg)
_(a6AB,t7AB)
_(l5AB,a6AB)
var e8AB=_n('text')
_rz(z,e8AB,'class',101,fYAB,oXAB,gg)
var b9AB=_oz(z,102,fYAB,oXAB,gg)
_(e8AB,b9AB)
_(l5AB,e8AB)
_(o4AB,l5AB)
_(o2AB,o4AB)
_(cZAB,o2AB)
return cZAB
}
oVAB.wxXCkey=2
_2z(z,93,xWAB,e,s,gg,oVAB,'item','__i0__','id')
_(aRAB,bUAB)
}
else{aRAB.wxVkey=2
var o0AB=_n('view')
_rz(z,o0AB,'class',103,e,s,gg)
var xABB=_oz(z,104,e,s,gg)
_(o0AB,xABB)
_(aRAB,o0AB)
}
aRAB.wxXCkey=1
_(f19,lQAB)
c29.wxXCkey=1
h39.wxXCkey=1
h39.wxXCkey=3
_(oZ9,f19)
_(r,oZ9)
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx0_XC_36";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx0_XC_36();	if (__vd_version_info__.delayedGwx) __wxAppCode__['package-system/issueFeedback/detail.wxml'] = [$gwx0_XC_36, './package-system/issueFeedback/detail.wxml'];else __wxAppCode__['package-system/issueFeedback/detail.wxml'] = $gwx0_XC_36( './package-system/issueFeedback/detail.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['package-system/issueFeedback/detail.wxss']=setCssToHead([".",[1],"detail-page.",[1],"data-v-67dd3a90{background:var(--color-bg);min-height:100vh}\n.",[1],"detail-card.",[1],"data-v-67dd3a90{background:#fff;border-radius:",[0,24],";box-shadow:0 ",[0,8]," ",[0,24]," rgba(31,41,55,.05);padding:",[0,28],"}\n.",[1],"detail-card__head.",[1],"data-v-67dd3a90{-webkit-align-items:flex-start;align-items:flex-start;display:-webkit-flex;display:flex;gap:",[0,24],";-webkit-justify-content:space-between;justify-content:space-between}\n.",[1],"detail-card__title.",[1],"data-v-67dd3a90{color:var(--color-main);-webkit-flex:1;flex:1;font-size:",[0,32],";font-weight:600;line-height:",[0,44],";white-space:normal;word-break:break-all}\n.",[1],"detail-card__section.",[1],"data-v-67dd3a90{color:var(--color-main);font-size:",[0,30],";font-weight:600;margin-bottom:",[0,20],"}\n.",[1],"detail-card__content.",[1],"data-v-67dd3a90{color:var(--color-content);font-size:",[0,28],";line-height:",[0,44],";white-space:pre-wrap;word-break:break-all}\n.",[1],"detail-card__content--collapsed.",[1],"data-v-67dd3a90{-webkit-box-orient:vertical;-webkit-line-clamp:4;display:-webkit-box;overflow:hidden;white-space:normal}\n.",[1],"content-toggle.",[1],"data-v-67dd3a90{color:var(--color-primary);font-size:",[0,24],";line-height:",[0,36],";margin-top:",[0,16],"}\n.",[1],"detail-grid.",[1],"data-v-67dd3a90{display:-webkit-flex;display:flex;-webkit-flex-wrap:wrap;flex-wrap:wrap;gap:",[0,28]," 0;margin-top:",[0,28],"}\n.",[1],"detail-grid__item.",[1],"data-v-67dd3a90{display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;gap:",[0,8],";width:50%}\n.",[1],"detail-grid__item.",[1],"data-v-67dd3a90:nth-child(2n){box-sizing:border-box;padding-left:",[0,40],"}\n.",[1],"detail-grid__label.",[1],"data-v-67dd3a90{color:var(--color-content);font-size:",[0,24],"}\n.",[1],"detail-grid__value.",[1],"data-v-67dd3a90{color:var(--color-main);font-size:",[0,28],";word-break:break-all}\n.",[1],"detail-grid__value-row.",[1],"data-v-67dd3a90{-webkit-flex-wrap:wrap;flex-wrap:wrap;gap:",[0,12],"}\n.",[1],"copy-btn.",[1],"data-v-67dd3a90,.",[1],"detail-grid__value-row.",[1],"data-v-67dd3a90{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex}\n.",[1],"copy-btn.",[1],"data-v-67dd3a90{background:var(--color-bg);border:",[0,1]," solid var(--color-border);border-radius:",[0,999],";-webkit-flex-shrink:0;flex-shrink:0;height:",[0,36],";-webkit-justify-content:center;justify-content:center;width:",[0,36],"}\n.",[1],"attachment-grid.",[1],"data-v-67dd3a90{display:-webkit-flex;display:flex;-webkit-flex-wrap:wrap;flex-wrap:wrap;gap:",[0,20],"}\n.",[1],"attachment-item.",[1],"data-v-67dd3a90{-webkit-align-items:center;align-items:center;background:#fffdf7;border:",[0,1]," dashed #ffd37a;border-radius:",[0,20],";box-sizing:border-box;display:-webkit-flex;display:flex;height:",[0,148],";-webkit-justify-content:center;justify-content:center;overflow:hidden;width:calc(33.33333% - ",[0,40],"/3)}\n.",[1],"attachment-video.",[1],"data-v-67dd3a90{height:100%;width:100%}\n.",[1],"attachment-file.",[1],"data-v-67dd3a90{-webkit-align-items:center;align-items:center;box-sizing:border-box;color:var(--color-primary);display:-webkit-flex;display:flex;font-size:",[0,26],";height:100%;-webkit-justify-content:center;justify-content:center;padding:",[0,16],";text-align:center;width:100%}\n.",[1],"timeline.",[1],"data-v-67dd3a90{position:relative}\n.",[1],"timeline__item.",[1],"data-v-67dd3a90{display:-webkit-flex;display:flex;gap:",[0,20],";padding-bottom:",[0,28],";position:relative}\n.",[1],"timeline__item.",[1],"data-v-67dd3a90:last-child{padding-bottom:0}\n.",[1],"timeline__item.",[1],"data-v-67dd3a90:after{background:var(--color-border);bottom:",[0,-6],";content:\x22\x22;left:",[0,11],";position:absolute;top:",[0,28],";width:",[0,2],"}\n.",[1],"timeline__item.",[1],"data-v-67dd3a90:last-child:after{display:none}\n.",[1],"timeline__dot.",[1],"data-v-67dd3a90{background:var(--color-primary);border-radius:50%;box-shadow:0 0 0 ",[0,8]," var(--color-primary-light);height:",[0,24],";margin-top:",[0,6],";position:relative;width:",[0,24],";z-index:1}\n.",[1],"timeline__content.",[1],"data-v-67dd3a90{-webkit-flex:1;flex:1}\n.",[1],"timeline__head.",[1],"data-v-67dd3a90{-webkit-align-items:center;align-items:center;display:-webkit-flex;display:flex;gap:",[0,16],";-webkit-justify-content:space-between;justify-content:space-between;margin-bottom:",[0,8],"}\n.",[1],"timeline__title.",[1],"data-v-67dd3a90{color:var(--color-main);font-size:",[0,28],";font-weight:600}\n.",[1],"timeline__time.",[1],"data-v-67dd3a90{line-height:",[0,36],"}\n.",[1],"empty-tip.",[1],"data-v-67dd3a90,.",[1],"timeline__time.",[1],"data-v-67dd3a90{color:var(--color-content);font-size:",[0,24],"}\n",],undefined,{path:"./package-system/issueFeedback/detail.wxss"});
}