$gwx2_XC_12=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx2_XC_12 || [];
function gz$gwx2_XC_12_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx2_XC_12_1)return __WXML_GLOBAL__.ops_cached.$gwx2_XC_12_1
__WXML_GLOBAL__.ops_cached.$gwx2_XC_12_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'__e'])
Z([3,'page data-v-4df0788b'])
Z([[4],[[5],[[4],[[5],[[5],[1,'refresherrefresh']],[[4],[[5],[[4],[[5],[[5],[1,'onRefresherRefresh']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([1,true])
Z([[7],[3,'refresherTriggered']])
Z(z[3])
Z([1,false])
Z([3,'toolbar data-v-4df0788b'])
Z(z[0])
Z([3,'data-v-4df0788b'])
Z([[4],[[5],[[4],[[5],[[5],[1,'change']],[[4],[[5],[[4],[[5],[[5],[1,'onDateChange']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([3,'date'])
Z([[7],[3,'statDate']])
Z([3,'date-picker data-v-4df0788b'])
Z([3,'date-text data-v-4df0788b'])
Z([a,[[7],[3,'statDate']]])
Z([3,'__l'])
Z(z[9])
Z([3,'#666'])
Z([3,'14'])
Z([3,'arrowdown'])
Z([3,'701f19db-1'])
Z([3,'card data-v-4df0788b'])
Z([3,'card-title-wrap data-v-4df0788b'])
Z([3,'card-title data-v-4df0788b'])
Z([3,'商品统计'])
Z([3,'stats-grid stats-grid-3 data-v-4df0788b'])
Z([3,'stat-item data-v-4df0788b'])
Z([3,'stat-label data-v-4df0788b'])
Z([3,'下单件数'])
Z([3,'stat-value data-v-4df0788b'])
Z([a,[[6],[[7],[3,'$root']],[3,'m0']]])
Z(z[27])
Z(z[28])
Z([3,'下单商品数'])
Z(z[30])
Z([a,[[6],[[7],[3,'$root']],[3,'m1']]])
Z(z[27])
Z(z[28])
Z([3,'下单毛重(斤)'])
Z(z[30])
Z([a,[[6],[[7],[3,'$root']],[3,'m2']]])
Z(z[22])
Z(z[23])
Z(z[24])
Z([3,'客户统计'])
Z([3,'stats-grid stats-grid-2 data-v-4df0788b'])
Z(z[27])
Z(z[28])
Z([3,'客户总数'])
Z(z[30])
Z([a,[[6],[[7],[3,'$root']],[3,'m3']]])
Z(z[27])
Z(z[28])
Z([3,'下单客户总数'])
Z(z[30])
Z([a,[[6],[[7],[3,'$root']],[3,'m4']]])
Z(z[22])
Z(z[23])
Z(z[24])
Z([3,'金额统计'])
Z(z[46])
Z(z[27])
Z(z[28])
Z([3,'销售金额(元)'])
Z([3,'stat-value stat-value-money data-v-4df0788b'])
Z([a,[[6],[[7],[3,'$root']],[3,'m5']]])
Z(z[27])
Z(z[28])
Z([3,'商品金额(元)'])
Z(z[30])
Z([a,[[6],[[7],[3,'$root']],[3,'m6']]])
Z(z[27])
Z(z[28])
Z([3,'服务费金额(元)'])
Z(z[30])
Z([a,[[6],[[7],[3,'$root']],[3,'m7']]])
Z(z[27])
Z(z[28])
Z([3,'运费金额(元)'])
Z(z[30])
Z([a,[[6],[[7],[3,'$root']],[3,'m8']]])
Z([[7],[3,'loading']])
Z([3,'loading-mask data-v-4df0788b'])
Z([3,'加载中...'])
})(__WXML_GLOBAL__.ops_cached.$gwx2_XC_12_1);return __WXML_GLOBAL__.ops_cached.$gwx2_XC_12_1
}
__WXML_GLOBAL__.ops_set.$gwx2_XC_12=z;
__WXML_GLOBAL__.ops_init.$gwx2_XC_12=true;
var x=['./sub-pages/merchant/user/city-warehouse-dashboard.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx2_XC_12_1()
var t5CB=_mz(z,'scroll-view',['bindrefresherrefresh',0,'class',1,'data-event-opts',1,'refresherEnabled',2,'refresherTriggered',3,'scrollY',4,'showScrollbar',5],[],e,s,gg)
var b7CB=_n('view')
_rz(z,b7CB,'class',7,e,s,gg)
var o8CB=_mz(z,'picker',['bindchange',8,'class',1,'data-event-opts',2,'mode',3,'value',4],[],e,s,gg)
var x9CB=_n('view')
_rz(z,x9CB,'class',13,e,s,gg)
var o0CB=_n('text')
_rz(z,o0CB,'class',14,e,s,gg)
var fADB=_oz(z,15,e,s,gg)
_(o0CB,fADB)
_(x9CB,o0CB)
var cBDB=_mz(z,'uni-icons',['bind:__l',16,'class',1,'color',2,'size',3,'type',4,'vueId',5],[],e,s,gg)
_(x9CB,cBDB)
_(o8CB,x9CB)
_(b7CB,o8CB)
_(t5CB,b7CB)
var hCDB=_n('view')
_rz(z,hCDB,'class',22,e,s,gg)
var oDDB=_n('view')
_rz(z,oDDB,'class',23,e,s,gg)
var cEDB=_n('text')
_rz(z,cEDB,'class',24,e,s,gg)
var oFDB=_oz(z,25,e,s,gg)
_(cEDB,oFDB)
_(oDDB,cEDB)
_(hCDB,oDDB)
var lGDB=_n('view')
_rz(z,lGDB,'class',26,e,s,gg)
var aHDB=_n('view')
_rz(z,aHDB,'class',27,e,s,gg)
var tIDB=_n('text')
_rz(z,tIDB,'class',28,e,s,gg)
var eJDB=_oz(z,29,e,s,gg)
_(tIDB,eJDB)
_(aHDB,tIDB)
var bKDB=_n('text')
_rz(z,bKDB,'class',30,e,s,gg)
var oLDB=_oz(z,31,e,s,gg)
_(bKDB,oLDB)
_(aHDB,bKDB)
_(lGDB,aHDB)
var xMDB=_n('view')
_rz(z,xMDB,'class',32,e,s,gg)
var oNDB=_n('text')
_rz(z,oNDB,'class',33,e,s,gg)
var fODB=_oz(z,34,e,s,gg)
_(oNDB,fODB)
_(xMDB,oNDB)
var cPDB=_n('text')
_rz(z,cPDB,'class',35,e,s,gg)
var hQDB=_oz(z,36,e,s,gg)
_(cPDB,hQDB)
_(xMDB,cPDB)
_(lGDB,xMDB)
var oRDB=_n('view')
_rz(z,oRDB,'class',37,e,s,gg)
var cSDB=_n('text')
_rz(z,cSDB,'class',38,e,s,gg)
var oTDB=_oz(z,39,e,s,gg)
_(cSDB,oTDB)
_(oRDB,cSDB)
var lUDB=_n('text')
_rz(z,lUDB,'class',40,e,s,gg)
var aVDB=_oz(z,41,e,s,gg)
_(lUDB,aVDB)
_(oRDB,lUDB)
_(lGDB,oRDB)
_(hCDB,lGDB)
_(t5CB,hCDB)
var tWDB=_n('view')
_rz(z,tWDB,'class',42,e,s,gg)
var eXDB=_n('view')
_rz(z,eXDB,'class',43,e,s,gg)
var bYDB=_n('text')
_rz(z,bYDB,'class',44,e,s,gg)
var oZDB=_oz(z,45,e,s,gg)
_(bYDB,oZDB)
_(eXDB,bYDB)
_(tWDB,eXDB)
var x1DB=_n('view')
_rz(z,x1DB,'class',46,e,s,gg)
var o2DB=_n('view')
_rz(z,o2DB,'class',47,e,s,gg)
var f3DB=_n('text')
_rz(z,f3DB,'class',48,e,s,gg)
var c4DB=_oz(z,49,e,s,gg)
_(f3DB,c4DB)
_(o2DB,f3DB)
var h5DB=_n('text')
_rz(z,h5DB,'class',50,e,s,gg)
var o6DB=_oz(z,51,e,s,gg)
_(h5DB,o6DB)
_(o2DB,h5DB)
_(x1DB,o2DB)
var c7DB=_n('view')
_rz(z,c7DB,'class',52,e,s,gg)
var o8DB=_n('text')
_rz(z,o8DB,'class',53,e,s,gg)
var l9DB=_oz(z,54,e,s,gg)
_(o8DB,l9DB)
_(c7DB,o8DB)
var a0DB=_n('text')
_rz(z,a0DB,'class',55,e,s,gg)
var tAEB=_oz(z,56,e,s,gg)
_(a0DB,tAEB)
_(c7DB,a0DB)
_(x1DB,c7DB)
_(tWDB,x1DB)
_(t5CB,tWDB)
var eBEB=_n('view')
_rz(z,eBEB,'class',57,e,s,gg)
var bCEB=_n('view')
_rz(z,bCEB,'class',58,e,s,gg)
var oDEB=_n('text')
_rz(z,oDEB,'class',59,e,s,gg)
var xEEB=_oz(z,60,e,s,gg)
_(oDEB,xEEB)
_(bCEB,oDEB)
_(eBEB,bCEB)
var oFEB=_n('view')
_rz(z,oFEB,'class',61,e,s,gg)
var fGEB=_n('view')
_rz(z,fGEB,'class',62,e,s,gg)
var cHEB=_n('text')
_rz(z,cHEB,'class',63,e,s,gg)
var hIEB=_oz(z,64,e,s,gg)
_(cHEB,hIEB)
_(fGEB,cHEB)
var oJEB=_n('text')
_rz(z,oJEB,'class',65,e,s,gg)
var cKEB=_oz(z,66,e,s,gg)
_(oJEB,cKEB)
_(fGEB,oJEB)
_(oFEB,fGEB)
var oLEB=_n('view')
_rz(z,oLEB,'class',67,e,s,gg)
var lMEB=_n('text')
_rz(z,lMEB,'class',68,e,s,gg)
var aNEB=_oz(z,69,e,s,gg)
_(lMEB,aNEB)
_(oLEB,lMEB)
var tOEB=_n('text')
_rz(z,tOEB,'class',70,e,s,gg)
var ePEB=_oz(z,71,e,s,gg)
_(tOEB,ePEB)
_(oLEB,tOEB)
_(oFEB,oLEB)
var bQEB=_n('view')
_rz(z,bQEB,'class',72,e,s,gg)
var oREB=_n('text')
_rz(z,oREB,'class',73,e,s,gg)
var xSEB=_oz(z,74,e,s,gg)
_(oREB,xSEB)
_(bQEB,oREB)
var oTEB=_n('text')
_rz(z,oTEB,'class',75,e,s,gg)
var fUEB=_oz(z,76,e,s,gg)
_(oTEB,fUEB)
_(bQEB,oTEB)
_(oFEB,bQEB)
var cVEB=_n('view')
_rz(z,cVEB,'class',77,e,s,gg)
var hWEB=_n('text')
_rz(z,hWEB,'class',78,e,s,gg)
var oXEB=_oz(z,79,e,s,gg)
_(hWEB,oXEB)
_(cVEB,hWEB)
var cYEB=_n('text')
_rz(z,cYEB,'class',80,e,s,gg)
var oZEB=_oz(z,81,e,s,gg)
_(cYEB,oZEB)
_(cVEB,cYEB)
_(oFEB,cVEB)
_(eBEB,oFEB)
_(t5CB,eBEB)
var e6CB=_v()
_(t5CB,e6CB)
if(_oz(z,82,e,s,gg)){e6CB.wxVkey=1
var l1EB=_n('view')
_rz(z,l1EB,'class',83,e,s,gg)
var a2EB=_oz(z,84,e,s,gg)
_(l1EB,a2EB)
_(e6CB,l1EB)
}
e6CB.wxXCkey=1
_(r,t5CB)
return r
}
e_[x[0]]={f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx2_XC_12";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx2_XC_12();	if (__vd_version_info__.delayedGwx) __wxAppCode__['sub-pages/merchant/user/city-warehouse-dashboard.wxml'] = [$gwx2_XC_12, './sub-pages/merchant/user/city-warehouse-dashboard.wxml'];else __wxAppCode__['sub-pages/merchant/user/city-warehouse-dashboard.wxml'] = $gwx2_XC_12( './sub-pages/merchant/user/city-warehouse-dashboard.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['sub-pages/merchant/user/city-warehouse-dashboard.wxss']=setCssToHead([".",[1],"page.",[1],"data-v-4df0788b{background:#f3f5f8;box-sizing:border-box;height:100vh;padding:",[0,20],"}\n.",[1],"toolbar.",[1],"data-v-4df0788b{display:-webkit-flex;display:flex;-webkit-justify-content:flex-start;justify-content:flex-start;margin-bottom:",[0,16],"}\n.",[1],"date-picker.",[1],"data-v-4df0788b{-webkit-align-items:center;align-items:center;background:#fff;border-radius:",[0,12],";box-shadow:0 ",[0,2]," ",[0,8]," rgba(0,0,0,.05);display:-webkit-inline-flex;display:inline-flex;gap:",[0,8],";padding:",[0,12]," ",[0,18],"}\n.",[1],"date-text.",[1],"data-v-4df0788b{color:#333;font-size:",[0,26],";font-weight:500}\n.",[1],"card.",[1],"data-v-4df0788b{background:#fff;border-radius:",[0,14],";margin-bottom:",[0,16],";padding:",[0,20],"}\n.",[1],"card-title-wrap.",[1],"data-v-4df0788b{margin-bottom:",[0,14],"}\n.",[1],"card-title.",[1],"data-v-4df0788b{color:#222;font-size:",[0,30],";font-weight:600}\n.",[1],"stats-grid.",[1],"data-v-4df0788b{grid-gap:",[0,12],";display:grid}\n.",[1],"stats-grid-3.",[1],"data-v-4df0788b{grid-template-columns:repeat(3,minmax(0,1fr))}\n.",[1],"stats-grid-2.",[1],"data-v-4df0788b{grid-template-columns:repeat(2,minmax(0,1fr))}\n.",[1],"stat-item.",[1],"data-v-4df0788b{background:#f8f9fb;border-radius:",[0,10],";padding:",[0,14]," ",[0,12],"}\n.",[1],"stat-label.",[1],"data-v-4df0788b{color:#7a7a7a;display:block;font-size:",[0,22],"}\n.",[1],"stat-value.",[1],"data-v-4df0788b{color:#2f6bff;display:block;font-size:",[0,34],";font-weight:700;line-height:1.1;margin-top:",[0,8],";word-break:break-all}\n.",[1],"stat-value-money.",[1],"data-v-4df0788b{color:#e85d04}\n.",[1],"loading-mask.",[1],"data-v-4df0788b{color:#777;font-size:",[0,24],";padding:",[0,20]," 0;text-align:center}\n",],undefined,{path:"./sub-pages/merchant/user/city-warehouse-dashboard.wxss"});
}